### PR TITLE
PR#11

### PR DESCRIPTION
**Pull request by cgiroux86**
Test PR

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/283)

### CODE REVIEW

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @chg1017)

**Review by chg1017 — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[newFile.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/283#-Md-0u6q9iJxACIAg1nz:-Md-0u6q9iJxACIAg1o-:b-8ax114) ([raw file](https://github.com/cgiroux86/test/blob/9833c120a4944507d6813c6023879290dbcb8f1a/newFile.js#L1)):*
> ```JavaScript
> console.log('HI!');
> ```

BLOCK

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[newFile.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/283#-Md-7fyM-2gk9MuWTYqM:-Md-7fyN2XyqFi2oCepp:b-89cz9v) ([raw file](https://github.com/cgiroux86/test/blob/9c85095309e646162bdc601816174a6f693da8f3/newFile.js#L1)):*
> ```JavaScript
> console.log('HI!!!');
> ```

Defer

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[newFile.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/283#-Md-7fyM-2gk9MuWTYqM:-Md-8Y7q3_pmFIJ-CQTO:bvuhxj1) ([raw file](https://github.com/cgiroux86/test/blob/9c85095309e646162bdc601816174a6f693da8f3/newFile.js#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Defer
</blockquote></details>

DEFER

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/283#-Md-B--UBmVOyQWPn7uU:-Md-B--UBmVOyQWPn7uV:b-nz2bq1) (no related file):*
BLOCKED

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/283#-Md-B--UBmVOyQWPn7uU:-Md-H1zY4kJmXt55E99i:byak2aa) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

BLOCKED
</blockquote></details>

PARKED 

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/283#-Md-B--UBmVOyQWPn7uU:-Md-K7De7nx8X7clIh6s:b-tup4b6) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

PARKED 
</blockquote></details>

PARKED AGAIN

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 1 at r2](http://localhost:8080/reviews/cgiroux86/test/283#-Md-KU4s8D8qAAqvicox:-Md-KU4s8D8qAAqvicoy:buqvhm1) ([raw file](https://github.com/cgiroux86/test/blob/4591b94c8b3aa0740e5fe3ef8f18b9fd854128c8/newFile.js#L1)):*
> ```JavaScript
> console.log('HI!!');
> ```

How do you like me now?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 1 at r2](http://localhost:8080/reviews/cgiroux86/test/283#-Md-Mrn5-5LLqRyCKnWp:-Md-Mrn5-5LLqRyCKnWq:b-wvvjat) ([raw file](https://github.com/cgiroux86/test/blob/4591b94c8b3aa0740e5fe3ef8f18b9fd854128c8/newFile.js#L1)):*
> ```JavaScript
> console.log('HI!!');
> ```

BLOCKER

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/283#-Md-7fyM-2gk9MuWTYqM:-Md25oa6CITvy85g_Qdq:b-8153x3) ([raw file](https://github.com/cgiroux86/test/blob/9c85095309e646162bdc601816174a6f693da8f3/newFile.js#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

DEFER      
</blockquote></details>

TEST

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/283)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[newFile.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/283#-Md-7fyM-2gk9MuWTYqM:-Md26S0KBKKIPkYcRffO:b-8153x3) ([raw file](https://github.com/cgiroux86/test/blob/9c85095309e646162bdc601816174a6f693da8f3/newFile.js#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

TEST 
</blockquote></details>

TEST

**Pull request merged**
