### PR TITLE
PR#11

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/162)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYu3Xf_DR4wQET1t0mf:-MYu3Xf_DR4wQET1t0mg:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Test

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYuqiPo9fkvgHAIEai6:-MYuqiPpDSiSukxqtskV:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L8)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

TEST

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYu3Xf_DR4wQET1t0mf:-MYuqCaM74dizrdQ3RRK:b-wztpzl) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L6)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

FOLLOWING UP

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYux63234His1dh2lmJ:-MYux63388ShB6lB0n_j:b-yy644e) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

HELLO WORLD!
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYuqiPo9fkvgHAIEai6:-MYv-c-c5SB7QboEc62e:bj21r0n) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

I don't know about this!

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYuqiPo9fkvgHAIEai6:-MYv2KgP7NqZWjrxRWUe:b-tiyd88) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

I don't know about this!
</blockquote></details>

HEY CHG!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYvC_aqDmpNZ012wS98:-MYvC_arCrffgrjYiDJi:b-vk126q) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

This might not be necessary either.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYvDFVl8GmMKec5WXhJ:-MYvDFVl8GmMKec5WXhK:bw1uxl9) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

This isn't needed.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYvDFVl8GmMKec5WXhJ:-MYvDFVl8GmMKec5WXhK:bw1uxkv) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

This isn't needed

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYvDFVl8GmMKec5WXhJ:-MYvDFVl8GmMKec5WXhK:b-txun3) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

This isn't needed!!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/162)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/162#-MYvDFVl8GmMKec5WXhJ:-MYvDFVl8GmMKec5WXhK:b-ps5duo) ([raw file](https://github.com/cgiroux86/test/blob/ad1899394076ff0472b0a1056bfdff280f3cad68/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

This isn't needed!!!

**Pull request merged**
