### PR TITLE
PR#3

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/168)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-MZy7uZA4s-Px6icEoYM:-MZy7uZB9cIqgNX--YTR:b-wvvgee) (no related file):*
BLOCKING

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-MZy8VT_3Kg2kZoArnbc:-MZy8VT_3Kg2kZoArnbd:bb76mu4) ([raw file](https://github.com/cgiroux86/test/blob/81b8d79466e2256fcdb71e1220afc0340fcfb9fc/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('8th commit');
> ```

Why?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-MZy8VT_3Kg2kZoArnbc:-MZy97GK7sQuHkawD_QR:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/81b8d79466e2256fcdb71e1220afc0340fcfb9fc/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Done.

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-MZy7uZA4s-Px6icEoYM:-MZy9CDZ-6MBLLCDFYC9:b-rfz40l) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

BLOCKING
</blockquote></details>

NOT DONE?

---

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-MZy7uZA4s-Px6icEoYM:-MZy9NYMAwjLMj61romf:b-896fix) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

NOT DONE?
</blockquote></details>

Done.

---

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: all files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-MZyANP2-4yoHXB5j5Dq:-MZyANP2-4yoHXB5j5Dr:bb76mu4) (no related file):*
Why?

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
draft

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168#-:-MZyad2U8DgShcQ7Ikzm:b-7rjd50)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1qMPHBsJDgp36DXCJ:-M_1qMPHBsJDgp36DXCK:b-fjlrc0) (no related file):*
UNPARK YOU @chg1017 

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1qMPHBsJDgp36DXCJ:-M_1qr2R7BKW37BmM9k8:bcpj36d) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

UNPARK YOU @chg1017 
</blockquote></details>

Try again! 

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1qMPHBsJDgp36DXCJ:-M_1rADy0bVvyB3Yr24P:bb74njr) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Try again! 
</blockquote></details>

Test

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-MZy8VT_3Kg2kZoArnbc:-M_1rQ9X0Uf1l3JzFi12:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/81b8d79466e2256fcdb71e1220afc0340fcfb9fc/mainfile1.js#L9)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Test

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1qMPHBsJDgp36DXCJ:-M_1rZ-xA3Tuai4fy1b7:bb74njr) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Test

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1qMPHBsJDgp36DXCJ:-M_1rrUKEjrSgUXP6RoY:bk0k3zo) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Another test

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1sURy9yzwYWgCRiVS:-M_1sURy9yzwYWgCRiVT:bb75ycc) (no related file):*
WHY?

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1sccT7mABrdCTGHfM:-M_1sccT7mABrdCTGHfN:bk0k3zo) (no related file):*
Another test

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1svUMEZeZ0uNYb_mD:-M_1svUMEZeZ0uNYb_mE:bggolhp) (no related file):*
Ok now I block

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1t80EEeByE-ywbqwa:-M_1t80EEeByE-ywbqwb:bk0k3zo) (no related file):*
Another test

---

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1t80EEeByE-ywbqwa:-M_1tFFA7e5lOGmH4irp:bqlt2vf) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Another test
</blockquote></details>

Here to block you @chg1017 

---

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1t80EEeByE-ywbqwa:-M_1tcIYBjrQX2928IOR:bb74njr) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Here to block you @chg1017 
</blockquote></details>

Test

---

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_1svUMEZeZ0uNYb_mD:-M_1vPZZ7CaZESjb9Fo4:b-875oab) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Ok now I block
</blockquote></details>

Hello

---

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_22Ymb3rQ1EcV_m8QO:bn8n322) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

direct send

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_234IM5pUheqe5LMos:b-1m8w7g) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

direct send
</blockquote></details>

One more

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_27KyR3FZ73EzFUcJY:bb7p34n) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

One more
</blockquote></details>

test

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_27UHz6ny-k3NsXarj:bb7p34n) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

test
</blockquote></details>

test

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_27gd7AgoFx_JYU1HQ:b-o8s5zo) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

test
</blockquote></details>

Theres battle lines being drawn

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_27zDw0EgmhXr0SpIh:b-urqfvu) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Theres battle lines being drawn
</blockquote></details>

Into your life it will creep

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_28MuR8rJpn4drluh7:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Into your life it will creep
</blockquote></details>

Test

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_28_qD-kfhesPmOFJ0:bk0k3zo) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Another test

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_29G_VEO-q0_8Pz1x7:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Another test
</blockquote></details>

Test

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_2ANjy8V1sxh3DfXHp:bmf37ap) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

parked?

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-M_22Ymb3rQ1EcV_m8QN:-M_2B4xD8jI1geYUbH1j:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/c885551ab3cc69bb90fdb80ecf71dd464ede5efa/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

parked?
</blockquote></details>

Test

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-MZy8VT_3Kg2kZoArnbc:-M_2KJd730NLdjPBSkzr:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/81b8d79466e2256fcdb71e1220afc0340fcfb9fc/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Test

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/168#-MZy8VT_3Kg2kZoArnbc:-M_2KfbP9sPpoJewlJp5:b-875oab) ([raw file](https://github.com/cgiroux86/test/blob/81b8d79466e2256fcdb71e1220afc0340fcfb9fc/mainfile1.js#L9)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Hello

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/168#-M_2RwAc0T5p3Xjad-1u:-M_2RwAc0T5p3Xjad-1v:b-l2xgr1) (no related file):*
Parking

---

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/168)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @cgiroux86)

**Pull request merged**
