### PR TITLE
PR#3

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/154)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/154#-MYM-W7D91naxSxGF6Uf:-MYM-W7E5C-Io6Ma5aSm:b-ea5slm) ([raw file](https://github.com/cgiroux86/test/blob/1d4c7dd010c616bc498d40e358168efb873d2fcf/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

Are we sure the whole world will see this?

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

**Review by girouxchris1017 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/154#-MYMh3Si-Bfwv7424fix:-MYMh3Si-Bfwv7424fiy:b-i0pckv) ([raw file](https://github.com/cgiroux86/test/blob/1d4c7dd010c616bc498d40e358168efb873d2fcf/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Why didn't we spell these out?

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/154#-MYMhoqV7JZSA2b6p9US:-MYMhoqV7JZSA2b6p9UT:b-h57uq0) ([raw file](https://github.com/cgiroux86/test/blob/fb462711adef60c7eb9787e0ab11ac4884fcc446/mainfile1.js#L7)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

Forgot this.

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 2 at r2](http://localhost:8080/reviews/cgiroux86/test/154#-MYPcohIEAB_SivaYI6w:-MYPcohIEAB_SivaYI6x:b1xrw3n) ([raw file](https://github.com/cgiroux86/test/blob/1d4c7dd010c616bc498d40e358168efb873d2fcf/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

I think we actually need this.

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/154#-MYQ78_BBK8HnIBNMsYn:-MYQ78_BBK8HnIBNMsYo:bry71m1) ([raw file](https://github.com/cgiroux86/test/blob/1d4c7dd010c616bc498d40e358168efb873d2fcf/mainfile1.js#L7)):*
> ```JavaScript
> console.log('4th commit');
> console.log('5th commit');
> console.log('6th commit');
> ```

Forgot about this

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/154)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017)

___
*[mainfile1.js, line 7 at r2](http://localhost:8080/reviews/cgiroux86/test/154#-MYQ78_BBK8HnIBNMsYn:-MYQWaAJ-6nh0cGTgwCm:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/1d4c7dd010c616bc498d40e358168efb873d2fcf/mainfile1.js#L7)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Follow up.  
</blockquote></details>

Done.

**Pull request merged**
