### PR TITLE
PR#7

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/172)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/172)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 10 at r1](http://localhost:8080/reviews/cgiroux86/test/172#-M_LDKAX0n8FYCF1y3aM:-M_LDKAX0n8FYCF1y3aN:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/c0418f2725fde1c1880ceddd19ec82c3ef895c71/mainfile1.js#L10)):*
> ```JavaScript
> console.log('7th commit');
> console.log('ALL YOU NEED IS');
> console.log('TEST');
> ```

Test

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/172#-M_LF2ZG0TuhgeYkyUd0:-M_LF2ZG0TuhgeYkyUd1:b-80jzue) ([raw file](https://github.com/cgiroux86/test/blob/c0418f2725fde1c1880ceddd19ec82c3ef895c71/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('ALL YOU NEED IS');
> ```

Test!

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/172)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/172#-M_LF2ZG0TuhgeYkyUd0:-M_LFfXAC3gl4cYSI5Fp:bccalvp) ([raw file](https://github.com/cgiroux86/test/blob/c0418f2725fde1c1880ceddd19ec82c3ef895c71/mainfile1.js#L9)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test!
</blockquote></details>

Different colors!

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/172)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 10 at r1](http://localhost:8080/reviews/cgiroux86/test/172#-M_LDKAX0n8FYCF1y3aM:-M_LDbHg008mFp29ZlqA:b32w0x) ([raw file](https://github.com/cgiroux86/test/blob/c0418f2725fde1c1880ceddd19ec82c3ef895c71/mainfile1.js#L10)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

OK

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/172)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/172#-M_LJBfy1UFJ71_ICtIa:-M_LJBfy1UFJ71_ICtIb:b-iee7jk) ([raw file](https://github.com/cgiroux86/test/blob/f331a69f94fd4a8ed9175b56554de5a307a31019/mainfile1.js#L8)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

Don't listen to a word I say...

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/172)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/172#-M_LJBfy1UFJ71_ICtIa:-M_LJbl17vqn9l-oVol4:bx2naiv) ([raw file](https://github.com/cgiroux86/test/blob/f331a69f94fd4a8ed9175b56554de5a307a31019/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Don't listen to a word I say...
</blockquote></details>

Blocking!

**Pull request merged**
