### PR TITLE
PR#9

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/174)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/174#-M_LPGlb4HjSttkR5WGB:-M_LPGlb4HjSttkR5WGC:bx2khhi) ([raw file](https://github.com/cgiroux86/test/blob/1f486b83b1e41fdec11c4cfd3076b910b955cf92/test.txt#L1)):*
> ```vimhelp
> HELLO REVIEWABLE!!
> ```

Blocked!

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/174#-M_LPGlb4HjSttkR5WGB:-M_LZllC4SSI8mCaH-TR:buuham1) ([raw file](https://github.com/cgiroux86/test/blob/1f486b83b1e41fdec11c4cfd3076b910b955cf92/test.txt#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Blocked! 
</blockquote></details>

Blocking!

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/174#-M_Ld1s53RnImOrBoWBE:-M_Ld1s53RnImOrBoWBF:bb74njr) (no related file):*
Test

---

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/174#-M_LPGlb4HjSttkR5WGB:-M_M48Lt9NO3YxXLuAHA:buuhcu4) ([raw file](https://github.com/cgiroux86/test/blob/1f486b83b1e41fdec11c4cfd3076b910b955cf92/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Blocking! 
</blockquote></details>

Blocking~ 
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/174#-M_M49__A-2HfhxJnD7U:-M_M49__A-2HfhxJnD7V:bb76mu4) ([raw file](https://github.com/cgiroux86/test/blob/d9428e136d7caa6c5abb64c873bd4c67b0c965e0/test.txt#L1)):*
> ```vimhelp
> HELLO REVIEWABLE!
> ```

Why?

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/174#-M_M49__A-2HfhxJnD7U:-M_M4ZvQ8rR09vD8eRzF:b5d0sz0) ([raw file](https://github.com/cgiroux86/test/blob/d9428e136d7caa6c5abb64c873bd4c67b0c965e0/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Hello!

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/174#-M_Ld1s53RnImOrBoWBE:-M_MEeRZEVKCsL9i0tTj:b-80jzuf) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Test 

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/174#-M_LPGlb4HjSttkR5WGB:-M_MInt2-j2pJnJPYz9m:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/1f486b83b1e41fdec11c4cfd3076b910b955cf92/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Working
</blockquote></details>

Test

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/174#-M_MkO6QAU-FWeKkn5lR:-M_MkO6QAU-FWeKkn5lS:bq9rnco) (no related file):*
Blocked?

---

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cgiroux86/test/174)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

*[a discussion](https://reviewable.io/reviews/cgiroux86/test/174#-M_WB5hS1pbCSC9Ntd5b:-M_WB5hTBvy1XW5lIwY5:bb74njr) (no related file):*
Test

---

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 2 of 3 files at r12, 3 of 3 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 2 of 3 files at r12, 3 of 3 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 7 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 2 of 3 files at r12, 2 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 2 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[//commits, line 2 at r17](http://localhost:8080/reviews/cgiroux86/test/174#-MaVrnFk56BpXyWy2gAq:-MaVrnFk56BpXyWy2gAr:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/412c81eb297ac372468d7f8be53144215f6a5ca4///commits#L2)):*
Test

**Comment by cgiroux86** [comment]
___
*[//commits, line 3 at r18](http://localhost:8080/reviews/cgiroux86/test/174#-MaVwsJO7uKp6SYTSI4b:-MaVwsJO7uKp6SYTSI4c:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/5312d5da3e65b37e92c27379917ba4adbb4b16b8///commits#L3)):*
Test

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 2 of 3 files at r12, 2 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 2 of 3 files at r12, 2 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 2 of 3 files at r12, 2 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 2 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 2 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 2 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 7 unresolved discussions (waiting on @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 1 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, 1 of 2 files at r14, 1 of 2 files at r15, 1 of 2 files at r16, 3 of 3 files at r17, 3 of 3 files at r18, 1 of 2 files at r19.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/174)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

___
*[//commits, line 20 at r19](http://localhost:8080/reviews/cgiroux86/test/174#-MaYHNd_5moUgX2dtCwx:-MaYHNd_5moUgX2dtCwy:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/1ea5cd7539306411d7bd6f4370b05df19097d775///commits#L20)):*
Test

**Pull request merged**
