### PR TITLE
PR#5

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/156)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/156)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/156#-MYeSlyUCflH9MpiPk78:-MYeSlyUCflH9MpiPk79:bbs7ida) ([raw file](https://github.com/cgiroux86/test/blob/8dd13c9fe9c0fa83a5c4a5caf89817a413623bb6/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLASSSTT OFFF!!!!!!!');
> ```

Role check!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/156)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/156#-MYeSlyUCflH9MpiPk78:-MYeT_B2D1TbfwCeVg2j:b-8zijrp) ([raw file](https://github.com/cgiroux86/test/blob/8dd13c9fe9c0fa83a5c4a5caf89817a413623bb6/file1.js#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Role check!
</blockquote></details>

Test comment!
___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/156#-MYeU9dC1HmdAwnUrRi0:-MYeU9dC1HmdAwnUrRi1:bzwis8) ([raw file](https://github.com/cgiroux86/test/blob/8dd13c9fe9c0fa83a5c4a5caf89817a413623bb6/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLASSSTT OFFF!!!!!!!');
> ```

Another blocker

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/156)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[file1.js, line 2 at r2](http://localhost:8080/reviews/cgiroux86/test/156#-MYeUl0w4yWRpAW6dpCR:-MYeUl0w4yWRpAW6dpCS:bgsy9bj) ([raw file](https://github.com/cgiroux86/test/blob/ebfb26b961c621976453456c1aee1ded527a5598/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLAST OFF!!!!!!!');
> ```

Unnecessary

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/156)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/156)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[file1.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/156#-MYel-MuAU7TFcM9r3RJ:-MYel-MuAU7TFcM9r3RK:b-xf4ek4) ([raw file](https://github.com/cgiroux86/test/blob/8dd13c9fe9c0fa83a5c4a5caf89817a413623bb6/file1.js#L1)):*
> ```JavaScript
> 
> ```

Role Change!
___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/156#-MYeU9dC1HmdAwnUrRi0:-MYeVGJq476Ys3haoL7A:bb73z5e) ([raw file](https://github.com/cgiroux86/test/blob/8dd13c9fe9c0fa83a5c4a5caf89817a413623bb6/file1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Another blocker
</blockquote></details>

TEXT
___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/156#-MYeVfaL5kZunp8lNiM_:-MYeVfaL5kZunp8lNiMa:b-wvvjmu) ([raw file](https://github.com/cgiroux86/test/blob/f13e65e776939340f9f32dac022d9d2897cc8097/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...!!!!!!!');
> ```

BLOCKED!
___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/156#-MYeXVjz36J4wNAQLNCH:-MYeXVjz36J4wNAQLNCI:b4fd1w1) ([raw file](https://github.com/cgiroux86/test/blob/f13e65e776939340f9f32dac022d9d2897cc8097/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...!!!!!!!');
> ```

TEST BLOCKER

**Pull request merged**
