### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/429)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
First?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

First?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRUHp0230Xw7pKKFpD):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Another?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?m

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?m
</blockquote></details>

Done.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/429)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/429#-MnRexTCE4VSTbRqBYiO):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Pull request merged**
