### PR TITLE
PR#6

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/157)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/157)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/157#-MYeoVO4852d2AkWF6eM:-MYeoVO59lJK4zyqzcK-:bb7p34n) ([raw file](https://github.com/cgiroux86/test/blob/fee4d5dcf27583e9ab11f862804ba0a7cce5ad22/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('8th commit');
> ```

test

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/157)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/157#-MYf4I_o5Rdp6yeFt83R:-MYf4I_p0rTcVk1g_cre:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/fee4d5dcf27583e9ab11f862804ba0a7cce5ad22/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('8th commit');
> ```

Test

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/157)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/157)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/157#-MYf_jPbDISY4ad856zd:-MYf_jPc4o_ModAEn8HJ:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/fee4d5dcf27583e9ab11f862804ba0a7cce5ad22/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Test

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/157)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/157#-MYf_xuX6ceA5_PInwzc:-MYf_xuZ0Z_8vCRIT9xu:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/fee4d5dcf27583e9ab11f862804ba0a7cce5ad22/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('8th commit');
> ```

Test

**Pull request merged**
