### PR TITLE
PR#14

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/165)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZJCkEo0nUGLeF8hLlW:-MZJCkEp4T2lkPZSMFeP:b-qbm566) (no related file):*
I think we need this file.

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZJCkEo0nUGLeF8hLlW:-MZJD-BX94-hK-BHDG5u:b-98kjs6) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

I think we need this file.
</blockquote></details>

I disagree..

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZJCkEo0nUGLeF8hLlW:-MZJHNsq0a-FaRoxJ9Vi:bb76mu4) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

I disagree..
</blockquote></details>

Why?

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZJCkEo0nUGLeF8hLlW:-MZJHSYHAlXCvly5KwF0:b-xd3vm6) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why?
</blockquote></details>

You're right.

---
___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZJHYzQ7hMCvKw9ctPa:blq1v7i) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
> ```Markdown
> # Code review files
> ```

How does this work?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[lastOne.js, line 4 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJIlqJEyT_83kBqkcB:-MZJIlqK1dG7W2OyWbRc:b-hyoy0j) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L4)):*
> ```JavaScript
> 
> console.log('first commit!');
> console.log('second commit!');
> ```

Why was this removed?

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[lastOne.js, line 4 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJIlqJEyT_83kBqkcB:-MZJItQF3ZPg11f-kSDP:b-1o2nzz) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L4)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

I'm not sure either...

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZJwKWS4ViXhuvGMJS6:b-srunom) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
> ```JavaScript
> // this is the last file!
> 
> console.log('first commit!');
> ```

New comment

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZJwUiU9qyAlrWpvQXX:b-jhra9c) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

How does this work?
</blockquote></details>

Not sure either.

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZJwWg36XFj3GHVvoVo:bh2icn1) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

New comment
</blockquote></details>

Another comment

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZO1LeGBPpZZiCnNAcK:b62rsm7) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Another comment
</blockquote></details>

Hi Hey!

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZO2JT94uf3uHsiFYps:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Not sure either.
</blockquote></details>

Test

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZO3214CUHy6B127eJ9:b60ozj1) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Testing 123

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZO39hD2g-CDgMTA5y5:bi9fwli) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Testing 123
</blockquote></details>

123465

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZO3Pzv0E24lJRiNmT1:bifnpnf) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

123465
</blockquote></details>

YEAH YEAH

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZO7DBW1c5APG4LsIWB:-MZO7DBW1c5APG4LsIWC:b-yy644e) (no related file):*
HELLO WORLD!

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZO7DBW1c5APG4LsIWB:-MZO7Or60MYVPX3NMUfQ:btykb1w) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

HELLO WORLD!
</blockquote></details>

Hello!

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZO7DBW1c5APG4LsIWB:-MZO7YREBO2BA-m5fbvO:b-pxlsmb) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hello!
</blockquote></details>

Failed?

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZO7DBW1c5APG4LsIWB:-MZO8SXd2w4X72XoZEMq:bfsebdp) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Failed?
</blockquote></details>

Failed again?

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZO7DBW1c5APG4LsIWB:-MZOAFYYBGOdlt9TsopX:b-460bqj) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Failed again?
</blockquote></details>

I took a walk

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZOBoN_CnV-V3_4MaaU:bb6wzsa) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Hi Hey!
</blockquote></details>

Hey!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZOEtH41dDl3FX7OVgv:b2nhgbb) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Hi Hey!
</blockquote></details>

Hey

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZOFVzf5urr_d-TmjNM:b2nhcbt) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hey
</blockquote></details>

Bye

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZOI4L75Aizr2kkJpX-:b-875o9w) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Bye
</blockquote></details>

Helo!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZOLmZvDBZMibnGv42d:bb6x6xt) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Helo!
</blockquote></details>

Hola

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZOMOsc7qZFSnO7N0ng:b-8b0xkr) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hola
</blockquote></details>

Adios

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @chg1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZONKDM2Wu3adfgG48L:b-8xymyq) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Adios
</blockquote></details>

Bon voyage!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZONTgv5PNDwmqMopQ7:-MZONTgv5PNDwmqMopQ8:bb6x6xt) (no related file):*
Hola

---

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZOOCt-7PiklDHxAhWa:btykb2q) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

YEAH YEAH
</blockquote></details>

Hello?

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZOSJ9V1YQ9yJaJJJ_i:bjqa4so) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hello?
</blockquote></details>

456789

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZOWhBpBkRVti7c8G0-:bi9fwko) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

456789
</blockquote></details>

123456

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZOdWQm14WaNfDJr4ni:b-8kqpwy) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

123456
</blockquote></details>

12345

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZOfIdNCmaRws35u-Y5:bb6jumf) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

12345
</blockquote></details>

5678

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZOgDg7AwJS5SvlYT5Y:b-8k69kh) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

5678
</blockquote></details>

23456

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[test.txt, line 1 at r3](http://localhost:8080/reviews/cgiroux86/test/165#-MZP7JeqBxDjW1HrrQpy:-MZP7JeqBxDjW1HrrQpz:b-tf6i54) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/test.txt#L1)):*
> ```vimhelp
> HELLO REVIEWABLE!!!
> ```

Why did you take these out?

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[lastOne.js, line 3 at r2](http://localhost:8080/reviews/cgiroux86/test/165#-MZJwKWS4ViXhuvGMJS5:-MZP7Nty4vpsABYDH40k:b2nhll9) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/lastOne.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Bon voyage!
</blockquote></details>

Ok.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/165#-MZP7XCSBLiiCtbDPAr6:-MZP7XCSBLiiCtbDPAr7:b-614c0j) (no related file):*
Top level!

---

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[files.md, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/165#-MZJHYzQ7hMCvKw9ctP_:-MZP7a0G9ULBX6DnuYaK:bb70hji) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/files.md#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

23456
</blockquote></details>

NVM.

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[lastOne.js, line 3 at r4](http://localhost:8080/reviews/cgiroux86/test/165#-MZSbgS90ffiCycEfXge:-MZSbgS90ffiCycEfXgf:brceeho) ([raw file](https://github.com/cgiroux86/test/blob/5316b1c11164107fd333ebe085a5fb97b071e9b2/lastOne.js#L3)):*
> ```JavaScript
> // this is the last file!
> 
> console.log('first commit!!!');
> ```

I liked more `!!`

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[test.txt, line 1 at r3](http://localhost:8080/reviews/cgiroux86/test/165#-MZP7JeqBxDjW1HrrQpy:-MZSg5DRBSwtQ8W4kJI1:bhd1tqb) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Why did you take these out?
</blockquote></details>

Yeah, why?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[file1.js, line 2 at r4](http://localhost:8080/reviews/cgiroux86/test/165#-MZYZ3v-0dYUARz1DORr:-MZYZ3v-0dYUARz1DORs:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/ea1c7d5d779e707ec22a795c525cc664bad0ee35/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLASTING OFF!!!!!!!');
> ```

Test

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/165)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Pull request merged**
