### PR TITLE
`FIRST COMMIT`

### PR DESCRIPTION
**Pull request by cgiroux86**
First PR

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/322)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/322)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-Mf8I8972HR_0AiBTbj7:-Mf8I898CbTYuqNA1-NK:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/—◯— commits#L2)):*
Test
___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-Mf8NFEm-HYyKkMrsLUW:-Mf8NFEm-HYyKkMrsLUX:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/968bd26fd044853661b32e98448fecbb1604fa9d/added.py#L1)):*
> ```Python
> print('This is an added file!');
> ```

Test

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/322)* status: all files reviewed, 2 unresolved discussions (waiting on @chg1017, @chg101786, and @girouxchris1017)

___
*[—◯— commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-Mf8I8972HR_0AiBTbj7:-Mf8gTbg1tCxenbLxU_s:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/—◯— commits#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.
___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-Mf8NFEm-HYyKkMrsLUW:-Mf8gU8vEz7SX-4SSWsV:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/968bd26fd044853661b32e98448fecbb1604fa9d/added.py#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Done.

**Review by chg101786 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/322)* status: all files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/322)* status: all files reviewed, commits not reviewed, all discussions resolved (waiting on @chg101786 and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/322)* status: all files reviewed (commits unreviewed), all discussions resolved (waiting on @chg101786 and @girouxchris1017)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfDhPkJC5tl3mvxPUG-:b-mxvfmi) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!!!
> ```



[sample-mp4-file.mp4](undefined/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/Kz_8edITcAHWGz1mRpp07Ba3/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
https://user-images.githubusercontent.com/59579733/126661462-3ab38677-b7c9-4957-8f98-facded3e75c8.mp4

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfDjvNhC75jIPKjIM5J:boy4fhc) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](undefined/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/Kz_8edITcAHWGz1mRpp07Ba3/sample-mp4-file.mp4)
</blockquote></details>





[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/HwZOorNHWHyGW0TChdIDSaE5/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfDrys93wI9rbs_SMdB:b21bux2) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/HwZOorNHWHyGW0TChdIDSaE5/sample-mp4-file.mp4)
</blockquote></details>

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfDvEBG4eWpjWmEJfWB:b-5kmmv2) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>


</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/fpEcaV6VTSxnLMugTqcE9UIh/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE0Ajw-95Q2KzWPwUi:bz0gxph) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/fpEcaV6VTSxnLMugTqcE9UIh/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/xl5y663HsEBcshr0dIYMrwXi/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE1apqCtjUBb7hb9Tq:b-ahb25l) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/xl5y663HsEBcshr0dIYMrwXi/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/rx5WP8-fNpo4YAzBTQL07eQV/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE1jIq9Fddvp9SwHiC:bwwtsif) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/rx5WP8-fNpo4YAzBTQL07eQV/sample-mp4-file.mp4)
</blockquote></details>

TEST
[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/ofknEOZtQRYFjeH8yf8Q-E5F/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE2VxMAFO3EeM6VH_3:b-lbmzry) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/ofknEOZtQRYFjeH8yf8Q-E5F/sample-mp4-file.mp4)

</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/j2IPHSZ4dUCx_BKoU7p_jtKN/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE2t01AtF6dn3prN7n:bbgqm0) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/j2IPHSZ4dUCx_BKoU7p_jtKN/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/fbEvzOUFVTpffxMDe8SVMdJB/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE3YeWAm8OeBAIsSza:b3u4qf3) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/fbEvzOUFVTpffxMDe8SVMdJB/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/Ih1Ui1ITgL3dT9iDPoNEaZef/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE4bYd4NjeTCN7BoK4:bbxnwj4) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/Ih1Ui1ITgL3dT9iDPoNEaZef/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/o3C_Da8tqg7VGaTni0PJ2lzJ/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/322#-MfDhPkJC5tl3mvxPUFz:-MfE5OCUDNugzuA8hN1Y:bhxxsfp) ([raw file](https://github.com/cgiroux86/test/blob/81d987dfc678e1525b326c95d6bde53264378347/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/o3C_Da8tqg7VGaTni0PJ2lzJ/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](http://localhost:8081/usercontent/images/reviewable-dev-chris-default-rtdb/59579733/Sepd2XBtMqu8pfqeSYqdnxX8/sample-mp4-file.mp4)

**Pull request merged**
