### PR TITLE
PR#13

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/164)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZICD-s4Ra-yXV7dCXD:-MZICD-t512InfikGLqF:bdoemdu) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('EVERYDAY!!!');
> ```

No need for capitals

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZICD-s4Ra-yXV7dCXD:-MZIDny3DUjmgRkLZpGy:b2nhll9) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

No need for capitals
</blockquote></details>

Ok.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZICD-s4Ra-yXV7dCXD:-MZIDtbu9V3Cy1xWn0jD:bfhqmln) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L9)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Ok.
</blockquote></details>

Not done?

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIEqCzCogTyCoYsew7:-MZIEqD-A7n5_Qv2bIho:bjfukpn) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L8)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

One more comment.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZICD-s4Ra-yXV7dCXD:-MZIFOj9BuCrmAv4KDFV:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 2 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIEqCzCogTyCoYsew7:-MZIFPeY5GOp5Ik6Wu8K:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L8)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

One more comment.
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIEqCzCogTyCoYsew7:-MZIFcgtBGmGUDhyKOE-:bgaftir) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L8)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIEqCzCogTyCoYsew7:-MZIGrZY3UuBIX5RqU8c:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L8)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Still not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIEqCzCogTyCoYsew7:-MZIHRuS2dhGae3hhLtt:b-nygdr6) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L8)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still no changes?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[test.txt, line 1 at r2](http://localhost:8080/reviews/cgiroux86/test/164#-MZINTiJ0t_L9Ux_gR3p:-MZINTiKEPyg0rrxYZk1:bmbzd2u) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/test.txt#L1)):*
> ```vimhelp
> HELLO REVIEWABLE!
> ```

Too many exclamations

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r2](http://localhost:8080/reviews/cgiroux86/test/164#-MZINTiJ0t_L9Ux_gR3p:-MZINlQdBNPq6l513YtY:bq9rql6) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/test.txt#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Too many exclamations
</blockquote></details>

Blocking

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[file1.js, line 2 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIO0rh-gGERZh5ig08:-MZIO0rh-gGERZh5ig09:b-n0jjte) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLAST OFF!!!!!!!');
> ```

Why did we take this out?

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIEqCzCogTyCoYsew7:-MZIOCa-AmJ-0vtGk6A7:b-fqxln3) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L8)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Still no changes?
</blockquote></details>

I don't see any either!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r2](http://localhost:8080/reviews/cgiroux86/test/164#-MZIPmiZ-442PPiaoKuq:-MZIPmi_Bbd3Yy58VTaH:bux06bt) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/test.txt#L1)):*
> ```vimhelp
> HELLO REVIEWABLE!
> ```

Another blocker!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r2](http://localhost:8080/reviews/cgiroux86/test/164#-MZIPmiZ-442PPiaoKuq:-MZITqkhBLk7obpMJGHA:b-c8gh9g) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/test.txt#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Another blocker!
</blockquote></details>

Here to comment!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 9 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIUnYu3QkpbRzIxQ1e:-MZIUnYu3QkpbRzIxQ1f:banhegd) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('EVERYDAY!!!');
> ```

Why did this get removed?

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZI_BQY8CzJ4u8wZ30k:-MZI_BQY8CzJ4u8wZ30l:bq9rql6) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

Blocking

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

___
*[file1.js, line 2 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIa4GaBFUOFP8tpDwc:-MZIa4GaBFUOFP8tpDwd:b-sl5zdk) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLAST OFF!!!!!!!');
> ```

Why is this removed?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

___
*[file1.js, line 2 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIb7yf0S7Ch3UjynDB:-MZIb7yf0S7Ch3UjynDC:b4t5qxo) ([raw file](https://github.com/cgiroux86/test/blob/977a1fc8e7a1251b5beff5f7ca282e5c221bb4f2/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...!!!!!!!');
> ```

Can you add it back please?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

___
*[file1.js, line 2 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIb7yf0S7Ch3UjynDB:-MZIbkOM3WnyJS5f1Kjt:b-vqdki8) ([raw file](https://github.com/cgiroux86/test/blob/977a1fc8e7a1251b5beff5f7ca282e5c221bb4f2/file1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Can you add it back please?
</blockquote></details>

PLEASE?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[file1.js, line 2 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIb7yf0S7Ch3UjynDB:-MZIfoz454fr0SHPW15T:b4kgaqq) ([raw file](https://github.com/cgiroux86/test/blob/977a1fc8e7a1251b5beff5f7ca282e5c221bb4f2/file1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

PLEASE?
</blockquote></details>

Not sure we need to.

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZI_BQY8CzJ4u8wZ30k:-MZIgOek92TQfAdAlh4Q:bybbbmn) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Blocking
</blockquote></details>

Why are we blocking this?

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[file1.js, line 2 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIa4GaBFUOFP8tpDwc:-MZInYvo6FLdafmlpQ1f:b-e3w52h) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/file1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

Not sure -- Do you know @cgiroux86

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIwB7tER-xZsN_ghop:-MZIwB7tER-xZsN_ghoq:b-vhkcs5) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L3)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> console.log('2nd commit');
> ```

Testing

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 9 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIUnYu3QkpbRzIxQ1e:-MZIwTv-3c5A4MqGYccu:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L9)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Why did this get removed?
</blockquote></details>

Test

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 6 at r3](http://localhost:8080/reviews/cgiroux86/test/164#-MZIwVCC8BmJHU381yxL:-MZIwVCC8BmJHU381yxM:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/537a54ea35a36d44f1d34e73b8f8cae026dcdc17/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Test

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZI_BQY8CzJ4u8wZ30k:-MZIxJuu7mpp7O0_uLns:bfq3gdj) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why are we blocking this?
</blockquote></details>

Not sure.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIwB7tER-xZsN_ghop:-MZIyqYd9x0qCdTHRx0R:b2fg8xb) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Testing
</blockquote></details>

Following up

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZI_BQY8CzJ4u8wZ30k:-MZIyxzE0zFc17lqsE5O:b5ozxgj) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Not sure.
</blockquote></details>

Do you know?

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZI_BQY8CzJ4u8wZ30k:-MZJ4ucn88esMfgi4iUk:b2nhkxn) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Do you know?
</blockquote></details>

No!

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/164)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/164#-MZIwB7tER-xZsN_ghop:-MZJ8CFN5cCqETnA2-UO:b7r5xui) ([raw file](https://github.com/cgiroux86/test/blob/c919f9e11d3305426a6a2d1f9c6a8456487667b0/mainfile1.js#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Following up
</blockquote></details>

Comment

**Pull request merged**
