### PR TITLE
PR#6

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/171)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/171)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/171#-M_L5rIRCt5IlvCuCSdt:-M_L5rIRCt5IlvCuCSdu:buuham1) (no related file):*
Blocking! 

---

**Comment by chg1017** [comment]
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/171#-M_L5rIRCt5IlvCuCSdt:-M_L5scB3RBMnvaONMip:bftas11) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Blocking! 
</blockquote></details>

Everyday! 

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/171)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/171#-M_L7QQA4MTQ7B1RddqX:-M_L7QQA4MTQ7B1RddqY:b-xqh0db) (no related file):*
I need to know! 

---

**Comment by girouxchris1017** [comment]
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/171#-M_L7QQA4MTQ7B1RddqX:-M_L7ccV57ju6DfYwyt0:bk0k3zo) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

I need to know! 
</blockquote></details>

Another test

---

**Comment by girouxchris1017** [comment]
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/171#-M_L5rIRCt5IlvCuCSdt:-M_L859oALUzibpdB4t3:bx2khhi) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Everyday! 
</blockquote></details>

Blocked! 

---

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/171)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/171#-M_L5rIRCt5IlvCuCSdt:-M_L86pU1wH_7OI3nhbr:ba8d681) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Blocked! 
</blockquote></details>

Really blocked~! 

---

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/171#-M_L88loACaUFkDMC55w:-M_L88loACaUFkDMC55x:b-xpl9ut) ([raw file](https://github.com/cgiroux86/test/blob/f6b7953df45364f793317c24f189fc1302d1aa9e/mainfile1.js#L5)):*
> ```JavaScript
> console.log('2nd commit');
> console.log('3rd commit');
> console.log('4th commit');
> ```

Draft comment

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/171)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/171#-M_L88loACaUFkDMC55w:-M_L8xCM8QPanvMGBXFI:b-5gbsf1) ([raw file](https://github.com/cgiroux86/test/blob/f6b7953df45364f793317c24f189fc1302d1aa9e/mainfile1.js#L5)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Draft comment
</blockquote></details>

BTW, should this unpack us??

**Review by chg1017 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/171)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/171)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/171#-M_LAjS1AQDw7SStUDnf:-M_LAjS22YCehZc3K6Ni:bq0pkvv) (no related file):*
Changing my role! 

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/171)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/171#-M_L88loACaUFkDMC55w:-M_L91ttD5u521F-JHVn:bycbs9y) ([raw file](https://github.com/cgiroux86/test/blob/f6b7953df45364f793317c24f189fc1302d1aa9e/mainfile1.js#L5)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

BTW, should this unpack us??
</blockquote></details>

ROLE?

**Pull request merged**
