### PR TITLE
PR#1

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/331)

### CODE REVIEW

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsTd-E7cSMs1pXKDIY:b-5xmit4) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!
> ```

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/aV_txPHkZnyy6YHXSn78DO4Y/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsUfv9EGCaQl-Co4Le:b-gb71l0) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/aV_txPHkZnyy6YHXSn78DO4Y/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/9fn3QuZZ6hhYNMseUeGo1Hgz/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsXsii9LueqgmXm5lk:b-fh9ki2) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/9fn3QuZZ6hhYNMseUeGo1Hgz/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/kxARwpK28P-Qq3nqcyBUiM3m/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
https://user-images.githubusercontent.com/59579733/127693885-5794de12-d007-4242-b70f-6e5defcd035e.mp4

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsbiP_ATg2j8Qe_lR5:b-adezyj) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/kxARwpK28P-Qq3nqcyBUiM3m/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/q2uZkrBmg_4z6DP8ort87Scy/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfscWt_1s4ZCu_PajZb:b-av35ju) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/q2uZkrBmg_4z6DP8ort87Scy/sample-mp4-file.mp4)
</blockquote></details>

TEST COMMENT mp4
[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/u8B8XELEspCuunSb5dGrD9RE/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mfse1j6AxlUra0uc5sT:b-lpvus0) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST COMMENT mp4
[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/u8B8XELEspCuunSb5dGrD9RE/sample-mp4-file.mp4)

</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/wBEoOcAOEPHD9iBPtVzVdbkS/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mfsf1ygDjDOhRaIFEcz:b-44otu5) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/wBEoOcAOEPHD9iBPtVzVdbkS/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/5s9naatpoFnUux-n6oMfPDgS/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mfsg4q-76u4mNvkutAh:b-6zeef2) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/5s9naatpoFnUux-n6oMfPDgS/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/YHi4yypZ39K4toENfszrKngZ/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsgLzv448Sb1Ku1GX5:b-r83yvj) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/YHi4yypZ39K4toENfszrKngZ/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/lh7Nsbp1UYHsayOdl1HTntyd/sample-mp4-file.mp4)

**Comment by chg1017** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfshRMsDUhwQXVfKJuU:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/lh7Nsbp1UYHsayOdl1HTntyd/sample-mp4-file.mp4)
</blockquote></details>

TEST

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mfsoi-q8wJWz_F-C87U:b-95kle1) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>


TEST

**Comment by chg101786** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfspRzX3HCZKj81_OMM:b-wvvgee) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

BLOCKING

**Comment by chg101786** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsuIS6EiE1ec3XBPzY:b-nz2bpn) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, chg101786 wrote…</i></summary><blockquote>

BLOCKING
</blockquote></details>

BLOCKER

**Comment by chg101786** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mfsuat1552pLM8AV2MD:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, chg101786 wrote…</i></summary><blockquote>

BLOCKER
</blockquote></details>

TEST

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsuUSfCm6kGzRcmQfQ:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, chg101786 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

TEST

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsxY4G1oYNRWs-nx7Z:b-ptbgie) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/HQ_OPkVHuXJMaF9om0tf9wTt/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsyM2k6zzgK9Aaayay:b96j5f9) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/HQ_OPkVHuXJMaF9om0tf9wTt/sample-mp4-file.mp4)
</blockquote></details>

TEST MP4 COMMENT!
[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/6Muv9y6ZjyxZmI_NsJM8e15I/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfsykPM-QE5RcwmmCKo:byfnq7d) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST MP4 COMMENT!
[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/6Muv9y6ZjyxZmI_NsJM8e15I/sample-mp4-file.mp4)

</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/eRMV1fhGGb9P4mz2M6b5-7y_/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-MfszNDoBbDdcV1lGzwi:bfwfs3w) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/eRMV1fhGGb9P4mz2M6b5-7y_/sample-mp4-file.mp4)
</blockquote></details>


[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/uqH6Ngu_ss_lCwLWlRB2ENdh/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mft7F019eoTnvlIR8Oz:b-c9ds12) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/uqH6Ngu_ss_lCwLWlRB2ENdh/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/_rCIXiW2224tyjlheTMiOrcM/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mft9DsD4i_vf00Wp7xv:b-lnp6n9) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/_rCIXiW2224tyjlheTMiOrcM/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/sB0pJwQtfT446GkDUAnY6t0o/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mg5gQh22Sk8DCvryCrq:bvgqiv1) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/sB0pJwQtfT446GkDUAnY6t0o/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/Rds6o6ZCylDygt6E4hjf0yJB/sample-mp4-file.mp4)
[sample-mp4-file copy 1.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/eAb7_2d_fDQ_r2fJhfitT7y4/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mg5kduR67ZshugPfi32:bmvzrqq) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/Rds6o6ZCylDygt6E4hjf0yJB/sample-mp4-file.mp4)
[sample-mp4-file copy 1.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/eAb7_2d_fDQ_r2fJhfitT7y4/sample-mp4-file.mp4)

</blockquote></details>


[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/PNVldwxOnLTHoSkPJZrcTewT/sample-mp4-file.mp4)
[sample-mp4-file copy 1.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/05TyfDRWorqISxJIDVz4L0HE/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mg5lDcL0SlA42d1xCXF:bc243f5) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>


[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/PNVldwxOnLTHoSkPJZrcTewT/sample-mp4-file.mp4)
[sample-mp4-file copy 1.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/05TyfDRWorqISxJIDVz4L0HE/sample-mp4-file.mp4)

</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/P0kmQ4mqiJLHuXiz-2LO-XvT/sample-mp4-file.mp4)
[sample-mp4-file copy 1.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/HrR2sIG8fb20aalsnZ7IX4gm/sample-mp4-file.mp4)

COMMENTS.... COMMENTS.... MORE COMMENTS...

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/331#-MfsTd-E7cSMs1pXKDIX:-Mg5tA9O8otOHZ17hWv9:b-2zhnzs) ([raw file](https://github.com/cgiroux86/test/blob/e18a0ea206074a8d2f197d3dbf065b7273edde21/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/P0kmQ4mqiJLHuXiz-2LO-XvT/sample-mp4-file.mp4)
[sample-mp4-file copy 1.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/HrR2sIG8fb20aalsnZ7IX4gm/sample-mp4-file.mp4)

COMMENTS.... COMMENTS.... MORE COMMENTS...
</blockquote></details>

HERE's some comments! 
[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/K1Q-M6B5ReLiGzRYjmnhhELV/sample-mp4-file.mp4)
[sample-mp4-file copy 1.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/xNOwvnq2_DTrNYzuhYo3vW1p/sample-mp4-file.mp4)
COMMENTS!

**Pull request merged**
