### PR TITLE
PR#4

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/155)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/155)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/155#-MYeFobw4irpuJH9cSUP:-MYeFobw4irpuJH9cSUQ:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/31c46ead751bc2b8fa28f5734fe8f39e1e34767c/mainfile1.js#L9)):*
> ```JavaScript
> console.log('7th commit');
> console.log('8th commit');
> console.log('9th commit');
> ```

Test

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/155)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/155#-MYeFobw4irpuJH9cSUP:-MYeIyOP2rm9GGR9plRd:b-x6jyri) ([raw file](https://github.com/cgiroux86/test/blob/31c46ead751bc2b8fa28f5734fe8f39e1e34767c/mainfile1.js#L9)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Working.

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/155)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/155#-MYeFobw4irpuJH9cSUP:-MYeLY6tEmKL6_6aohM_:b-7o7y6i) ([raw file](https://github.com/cgiroux86/test/blob/31c46ead751bc2b8fa28f5734fe8f39e1e34767c/mainfile1.js#L9)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Working.
</blockquote></details>

No Changes?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/155)* status: all files reviewed, 1 unresolved discussion (waiting on @chg1017 and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/155#-MYeFobw4irpuJH9cSUP:-MYeLzJLDY0B-HIs2bbA:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/31c46ead751bc2b8fa28f5734fe8f39e1e34767c/mainfile1.js#L9)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

No Changes?
</blockquote></details>

Done.

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/155)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/155#-MYeFobw4irpuJH9cSUP:-MYeNPbb7_6gtIp5zuxw:b-nygdr6) ([raw file](https://github.com/cgiroux86/test/blob/31c46ead751bc2b8fa28f5734fe8f39e1e34767c/mainfile1.js#L9)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still no changes?

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/155)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/155#-MYeFobw4irpuJH9cSUP:-MYePvRP9eCnfrQyJpBx:b-e1czuy) ([raw file](https://github.com/cgiroux86/test/blob/31c46ead751bc2b8fa28f5734fe8f39e1e34767c/mainfile1.js#L9)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Still no changes?
</blockquote></details>

Test comment

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/155)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/155#-MYeQ6o05hFlAIMHa70d:-MYeQ6o05hFlAIMHa70e:b-ce2v6l) ([raw file](https://github.com/cgiroux86/test/blob/904e7c1914879732c7545d9181132f16b63acddb/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

I think this is necessary.

**Pull request merged**
