### PR TITLE
PR#4

### PR DESCRIPTION
**Pull request by cgiroux86**
TEST PR

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/279)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[file1.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyQd7d-KDEqs8ki830:-McyQd7d-KDEqs8ki831:b-wvvgee) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/file1.js#L1)):*
> ```JavaScript
> console.log('HELLO WORLD!!!!!');
> ```

BLOCKING

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by chg1017 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[file1.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyQd7d-KDEqs8ki830:-McyRasyAE6mbxjOEsz2:brk3bdf) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/file1.js#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

BLOCKING
</blockquote></details>

DEFER

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyReyhE96ysVAYLQ1w:-McyReyhE96ysVAYLQ1x:b-wvvgee) ([raw file](https://github.com/cgiroux86/test/blob/cc79f473f4bff87f904a49f07c49e86db3d0841e/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!!!
> ```

BLOCKING

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyRjpcAJQeywfZh2Vy:-McyRjpcAJQeywfZh2Vz:b-2dc2gj) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!
> ```

PARKING

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyRjpcAJQeywfZh2Vy:-McyRngCAGElblObWpzF:by6wbtu) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/test.txt#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

PARKING 
</blockquote></details>

REPARK

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyRjpcAJQeywfZh2Vy:-Mcyc2fTDNmdJhT1m0SQ:bb71c33) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

REPARK
</blockquote></details>

PARK

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyRjpcAJQeywfZh2Vy:-Mcyc5txD5o6U7ouYBp7:by6wbtu) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/test.txt#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

PARK
</blockquote></details>

REPARK

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyRjpcAJQeywfZh2Vy:-McycTaF0WYYL5qXSr2h:bb720lr) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

REPARK
</blockquote></details>

Park

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyRjpcAJQeywfZh2Vy:-McycWJF3XtsEFkhTaB8:by7hfxe) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/test.txt#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Park
</blockquote></details>

REpark

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyReyhE96ysVAYLQ1w:-McydWan7xArlow0TiBL:b-yflgp4) ([raw file](https://github.com/cgiroux86/test/blob/cc79f473f4bff87f904a49f07c49e86db3d0841e/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

BLOCKING
</blockquote></details>

WHAT?

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/279)* status: all files reviewed, 3 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[file1.js, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/279#-McyQd7d-KDEqs8ki830:-Mcyf9EN4t0CmNzO84mB:b-o8503t) ([raw file](https://github.com/cgiroux86/test/blob/f8ab0a6b95a5b8c5ebe261a765dd98d278477002/file1.js#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

DEFER 
</blockquote></details>

TEST DEFER

**Pull request merged**
