### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by cgiroux86**
TEST PR

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/342)

### CODE REVIEW

**Comment by cgiroux86** [comment]
___
*[hello_world.py, line 4 at r1](https://reviewable.io/reviews/cgiroux86/test/342#-MgLHi-l0ZzFVy0ehFQr:-MgLHVVmE8H0VzIxLx5L:b-ejdnxg) ([raw file](https://github.com/cgiroux86/test/blob/a70cccf6c26c5cfa81cd2af2f50a7b03f4d78cb3/hello_world.py#L4)):*
> ```Python
> 
> for world in hello:
>     print(f"HELLO {world.upper()}!")
> ```

[world.mov](https://files.reviewableusercontent.io/images/reviewable/59579733/edUTjSF1xII85hI27_DSiTWx/world.mov)

**Comment by cgiroux86** [comment]
___
*[hello.py, line 4 at r1](http://localhost:8080/reviews/cgiroux86/test/342#-MgLc0_d6mPiGnsVxjUV:-MgLc0_d6mPiGnsVxjUW:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/b06f6ee0a27e38e8020e2aa3548762455ed7f554/hello.py#L4)):*
> ```Python
> 
> for world in hello:
>     print(f"HELLO {world.upper()}!!")
> ```

TEST

**Comment by cgiroux86** [comment]
___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/342#-MgLc4t8EzCkqrJUis_X:-MgLc4t95lcngB3X_dcS:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/a70cccf6c26c5cfa81cd2af2f50a7b03f4d78cb3/-- commits#L2)):*
TEST

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/342)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chg1017, @chg101786, and @girouxchris1017)

**Comment by cgiroux86** [comment]
___
*[hello_world.py, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/342#-MgLoAtGBV3eP3eVRVkI:-MgLoAtGBV3eP3eVRVkJ:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/a70cccf6c26c5cfa81cd2af2f50a7b03f4d78cb3/hello_world.py#L2)):*
> ```Python
> hello = ['world', 'world', 'world', 'world']
> ```

TEST

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/342)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @chg1017, @chg101786, and @girouxchris1017)

___
*[test.txt, line 1 at r2](http://localhost:8080/reviews/cgiroux86/test/342#-MgM0hlTCNqd2gKbkKlB:-MgM0hlU7wy1Vfek_f7q:bnd7i9v) ([raw file](https://github.com/cgiroux86/test/blob/b06f6ee0a27e38e8020e2aa3548762455ed7f554/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!!
> ```

TESTING...

**Comment by cgiroux86** [comment]
___
*[small/small_diff_12.html, line 5 at r3](http://localhost:8080/reviews/cgiroux86/test/342#-MgMDdfnA3drlToBcQC0:-MgMDdfnA3drlToBcQC1:b-3sz5n9) ([raw file](https://github.com/cgiroux86/test/blob/5f92b17efb70d471c97288fd8a06f55e06698daf/small/small_diff_12.html#L5)):*
> ```HTML
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non quaeritur autem quid naturae tuae consentaneum sit, sed quid disciplinae. Hoc autem loco tantum explicemus haec honesta, quae dico, praeterquam quod nosmet ipsos diligamus, praeterea suapte natura per se esse expetenda. Facit igitur Lucius noster prudenter, qui audire de summo bono potissimum velit; Videmus igitur ut conquiescere ne infantes quidem possint. Est igitur officium eius generis, quod nec in bonis ponatur nec in contrariis. Quis est enim, in quo sit cupiditas, quin recte cupidus dici possit? Duo Reges: constructio interrete. Sed erat aequius Triarium aliquid de dissensione nostra iudicare. Pungunt quasi aculeis interrogatiunculis angustis, quibus etiam qui assentiuntur nihil commutantur animo et idem abeunt, qui venerant. Ergo adhuc, quantum equidem intellego, causa non videtur fuisse mutandi nominis. Nobis Heracleotes ille Dionysius flagitiose descivisse videtur a Stoicis propter oculorum dolorem. Idemne potest esse dies saepius, qui semel fuit? An vero, inquit, quisquam potest probare, quod perceptfum, quod. </p>
> 
> <p>Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. De quibus etsi a Chrysippo maxime est elaboratum, tamen a Zenone minus multo quam ab antiquis; Num igitur eum postea censes anxio animo aut sollicito fuisse? Nec vero pietas adversus deos nec quanta iis gratia debeatur sine explicatione naturae intellegi potest. Hoc autem tempore, etsi multa in omni parte Athenarum sunt in ipsis locis indicia summorum virorum, tamen ego illa moveor exhedra. Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. Et quidem saepe quaerimus verbum Latinum par Graeco et quod idem valeat; Quo minus animus a se ipse dissidens secumque discordans gustare partem ullam liquidae voluptatis et liberae potest. </p>
> ```

TEST COMMENT!

**Comment by cgiroux86** [comment]
___
*[-- commits, line 5 at r2](http://localhost:8080/reviews/cgiroux86/test/342#-MgMPe8Z8J4Nho6aOqdj:-MgMPe8Z8J4Nho6aOqdk:b-srunom) ([raw file](https://github.com/cgiroux86/test/blob/7bd974cd9a7b12d0dbb98759c4aace0e783cd276/-- commits#L5)):*
New comment

**Comment by cgiroux86** [comment]
___
*[small/small_diff_0.html, line 13 at r3](http://localhost:8080/reviews/cgiroux86/test/342#-MgMBrLt1th4ikMgtXLt:-MgMBrLuAjpb1Y-Fb4Fy:b-3sz5n9) ([raw file](https://github.com/cgiroux86/test/blob/5f92b17efb70d471c97288fd8a06f55e06698daf/small/small_diff_0.html#L13)):*
> ```HTML
> <p>Quid igitur dubitamus in tota eius natura quaerere quid sit effectum? Atque haec contra Aristippum, qui eam voluptatem non modo summam, sed solam etiam ducit, quam omnes unam appellamus voluptatem. Immo sit sane nihil melius, inquam-nondum enim id quaero-, num propterea idem voluptas est, quod, ut ita dicam, indolentia? Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. An hoc usque quaque, aliter in vita? Ego vero volo in virtute vim esse quam maximam; Ne vitationem quidem doloris ipsam per se quisquam in rebus expetendis putavit, nisi etiam evitare posset. Tu vero, inquam, ducas licet, si sequetur; Ergo infelix una molestia, fellx rursus, cum is ipse anulus in praecordiis piscis inventus est? Levatio igitur vitiorum magna fit in iis, qui habent ad virtutem progressionis aliquantum. Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? </p>
> 
> <h4>Quis contra in illa aetate pudorem, constantiam, etiamsi sua nihil intersit, non tamen diligat?</h4>
> ```

TEST COMMENT!

**Review by cgiroux86 — COMMENTED** [review]
:lgtm:

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/342#-:-MgQVyiqADWOk3l0l5nn:bnfp4nl)* status: 0 of 23 files reviewed, 8 unresolved discussions (waiting on @chg1017, @chg101786, and @girouxchris1017)

___
*[small/small_diff_10.html, line 9 at r3](http://localhost:8080/reviews/cgiroux86/test/342#-MgMCoP24YXcZzzt17ez:-MgMCoP24YXcZzzt17f-:bk0k3zo) ([raw file](https://github.com/cgiroux86/test/blob/5f92b17efb70d471c97288fd8a06f55e06698daf/small/small_diff_10.html#L9)):*
> ```HTML
> <p>Aut pertinacissimus fueris, si in eo perstiteris ad corpus ea, quae dixi, referri, aut deserueris totam Epicuri voluptatem, si negaveris. Atqui iste locus est, Piso, tibi etiam atque etiam confirmandus, inquam; Cum id quoque, ut cupiebat, audivisset, evelli iussit eam, qua erat transfixus, hastam. Tu enim ista lenius, hic Stoicorum more nos vexat. Ita relinquet duas, de quibus etiam atque etiam consideret. Quae tamen a te agetur non melior, quam illae sunt, quas interdum optines. Cur post Tarentum ad Archytam? De hominibus dici non necesse est. Piso igitur hoc modo, vir optimus tuique, ut scis, amantissimus. Eam stabilem appellas. Quid enim de amicitia statueris utilitatis causa expetenda vides. </p>
> 
> <p>Innumerabilia dici possunt in hanc sententiam, sed non necesse est. Sic igitur in homine perfectio ista in eo potissimum, quod est optimum, id est in virtute, laudatur. Sed ad haec, nisi molestum est, habeo quae velim. Aderamus nos quidem adolescentes, sed multi amplissimi viri, quorum nemo censuit plus Fadiae dandum, quam posset ad eam lege Voconia pervenire. Ne id quidem, nisi multa annorum intercesserint milia, ut omnium siderum eodem, unde profecta sint, fiat ad unum tempus reversio. Tum Piso: Quoniam igitur aliquid omnes, quid Lucius noster? Ergo ita: non posse honeste vivi, nisi honeste vivatur? </p>
> ```

Another test

**Review by chg1017 — APPROVED** [review]
:lgtm:

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/342#-:-MgQWjxk538Qn6gAC8rF:bnfp4nl)* status: 0 of 23 files reviewed, 8 unresolved discussions (waiting on @chg101786 and @girouxchris1017)

**Comment by chg1017** [comment]
:lgtm_cancel:

**Comment by chg1017** [comment]
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/342#-MgQXASj55uuATQr5Mfx:-MgQXASj55uuATQr5Mfy:bg7igkv) (no related file):*
:lgtm: 

---

**Review by cgiroux86 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cgiroux86/test/342#-:-MgQXSI69q7c_UL5T70i:bnfp4nl)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @chg101786 and @girouxchris1017)

**Review by chg101786 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cgiroux86/test/342#-:-MgQXl4s3yPoT0LxmDLG:bnfp4nl)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
:lgtm_cancel: :

> *[Reviewable](https://reviewable.io/reviews/cgiroux86/test/342#-:-MgQXa4Z18f4Wk0PSsHW:b-qh6tr0)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @chg101786 and @girouxchris1017)

**Review by chg101786 — COMMENTED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/cgiroux86/test/342#-:-MgQ_X9tBPUeAEJU2_Bd:b8b79qu)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cgiroux86/test/342#-:-MgRXrODDPuh4yOMOjXK:bnfp4nl)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Pull request merged**
