### PR TITLE
PR#7

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/173)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/173#-M_LK_Nt1V061yQeAYNz:-M_LK_Nt1V061yQeAYO-:b-mxlqti) ([raw file](https://github.com/cgiroux86/test/blob/3e3df21fcc3529aba45688fab827d43223b01fe3/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLAST OFF!!!!!!!');
> ```

Why is this out?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/173#-M_LK_Nt1V061yQeAYNz:-M_LLNqQDs-_4pWHi7De:b-x6jyri) ([raw file](https://github.com/cgiroux86/test/blob/3e3df21fcc3529aba45688fab827d43223b01fe3/file1.js#L2)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Why is this out?
</blockquote></details>

Working.

**Review by chg1017 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/173#-M_LK_Nt1V061yQeAYNz:-M_LM--h5iEX7h1Gm_Ty:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/3e3df21fcc3529aba45688fab827d43223b01fe3/file1.js#L2)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Working.
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/173#-M_LMoKX1jTFklOHBc6Y:-M_LMoKYAmsqWJf_FJja:bchyey) ([raw file](https://github.com/cgiroux86/test/blob/3e3df21fcc3529aba45688fab827d43223b01fe3/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...BLAST OFF!!!!!!!');
> ```

Why is this out again?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/173#-M_LNIZn6fyjOY_s4TDf:-M_LNIZn6fyjOY_s4TDg:br86v15) ([raw file](https://github.com/cgiroux86/test/blob/503e061d432d074a29ea43cd43351e43d4e1e5ab/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...!!!!!!!');
> ```

Block!

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/173#-M_LN_jr9K0Y42SxNoc5:-M_LMRv90v8rIdt4Ac03:byditns) (no related file):*
Does this change the timestamp?

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[file1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/173#-M_LO9r0EWmeQUNARq9J:-M_LO9r1CD7lZftMlwf9:b-supnp5) ([raw file](https://github.com/cgiroux86/test/blob/503e061d432d074a29ea43cd43351e43d4e1e5ab/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0...!!!!!!!');
> ```

Testing roles!

**Review by girouxchris1017 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/173)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

**Pull request merged**
