### PR TITLE
PR#5

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/170)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_Kzt399cWXnNLaOUb9:banhegd) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('8th commit');
> ```

Why did this get removed?

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_KzwiE6kiVPMO7bzrR:-M_KzwiF0Dys0bK_Srxb:bdlo8s8) ([raw file](https://github.com/cgiroux86/test/blob/cf629693fbc2365d49fcfc6c16f6d834918567e1/mainfile1.js#L8)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

Test draft

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_L-F31-lng5Bint92J:-M_L-F31-lng5Bint92K:b-k7gr8m) ([raw file](https://github.com/cgiroux86/test/blob/cf629693fbc2365d49fcfc6c16f6d834918567e1/mainfile1.js#L8)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

Direct send

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_L-j0s8pTUBSF7RGoM:-M_L-j0t5bGOQPmNrvlj:bs4oocu) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L8)):*
> ```JavaScript
> console.log('5th commit');
> console.log('6th commit');
> console.log('7th commit');
> ```

Direct

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_L-j0s8pTUBSF7RGoM:-M_L0-1iBRER3Br2Uqvy:b-yrbccv) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Direct
</blockquote></details>

Direct draft

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_L-j0s8pTUBSF7RGoM:-M_L0DIO1C9C1tjgULaz:basxc6t) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Direct draft 
</blockquote></details>

NO LOG?

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L0Oph4FVQ-f-SciJs:bs4oocu) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Direct

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_L0_daBmu8MDnw4GbJ:-M_L0_daBmu8MDnw4GbK:b-24mmc2) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Test direct

**Comment by chg1017** [comment]
___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_L-j0s8pTUBSF7RGoM:-M_L11_z18Mv_w3rj8Pj:b-4cuzid) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

NO LOG?
</blockquote></details>

Deferred?

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[mainfile1.js, line 8 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_L-j0s8pTUBSF7RGoM:-M_L1WuF9xyGYcoy6XJN:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L8)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Deferred?
</blockquote></details>

Test

**Comment by girouxchris1017** [comment]
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/170#-M_L2WQg8kw_WXHGvJLg:-M_L2WQg8kw_WXHGvJLh:b-k7gr8m) (no related file):*
Direct send

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/170#-M_L2WQg8kw_WXHGvJLg:-M_L2gPs7HL4Yr6ZOgol:buuham1) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Direct send
</blockquote></details>

Blocking! 

---

**Comment by chg1017** [comment]
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/170#-M_L2WQg8kw_WXHGvJLg:-M_L2iBOCwVhxH0rvnFk:b-80jzuf) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Blocking! 
</blockquote></details>

Test 

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/170#-M_L2WQg8kw_WXHGvJLg:-M_L3CtaEjR9AqFjrYNX:b-80jzuf) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test 
</blockquote></details>

Test 

---

**Comment by chg1017** [comment]
*[a discussion](http://localhost:8080/reviews/cgiroux86/test/170#-M_L2WQg8kw_WXHGvJLg:-M_L3WAo9HZGxGBnsNzl:b-yrbccv) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Another test 
</blockquote></details>

Direct draft 

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/170#-M_L2WQg8kw_WXHGvJLg:-M_L3o1D5cC9SvvOlKBZ:b-luko5b) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Direct draft 
</blockquote></details>

Another draft 

---

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L3xq04JneszkZxWbM:btykb2q) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hey! 
</blockquote></details>

Hello?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L40Zk6IDPkNyeQeJp:b-80jzuf) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hello?
</blockquote></details>

Test

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L41baBCAMdR2QQ5Sf:b-80jzuf) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test 
</blockquote></details>

Test

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L44S5-GkJRyMVn7co:btykb2q) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test 
</blockquote></details>

Hello?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/170)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L4ugGC1mUhf7hd_6U:b-80jzuf) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Hello?
</blockquote></details>

Test

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L4vsB5lFt5C-_BTUb:bkfdc4l) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test 
</blockquote></details>

Draft comment

**Comment by girouxchris1017** [comment]
___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/170#-M_Kzt399cWXnNLaOUb8:-M_L5OGO2MX2c59wJOOR:b-uzshfb) ([raw file](https://github.com/cgiroux86/test/blob/347302790e2f9492ededa59a4aa7c2c0d5063413/mainfile1.js#L9)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test 
</blockquote></details>

Why is this changing?

**Pull request merged**
