### PR TITLE
PR#1

### PR DESCRIPTION
**Pull request by cgiroux86**
TEST PR

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/295)

### CODE REVIEW

**Comment by girouxchris1017** [comment]
___
*[added.py, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/295#-MdMseM13lerCJ-M9y5A:-MdMseM13lerCJ-M9y5B:b7r5xui) ([raw file](https://github.com/cgiroux86/test/blob/b97ff217846079c33049d4d02d81a5ed25467026/added.py#L1)):*
> ```Python
> print('This is an added file!');
> ```

Comment

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/295)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/295#-MdMt6qY0c1FDqcqHnAM:-MdMt6qZ21u-yK5Jl3Ro:bb74njr) (no related file):*
Test

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/295)* status: 1 of 151 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_0.html, line 8 at r2](http://localhost:8080/reviews/cgiroux86/test/295#-MdMvSiv2cdlSzCD1nqM:-MdMvSiv2cdlSzCD1nqN:b-e1czuy) ([raw file](https://github.com/cgiroux86/test/blob/f4b239814d77a9915227c78404ba7e134ece10aa/large/large_diff_0.html#L8)):*
> ```HTML
> 
> <p>Sed est forma eius disciplinae, sicut fere ceterarum, triplex: una pars est naturae, disserendi altera, vivendi tertia. Et tamen quid attinet luxuriosis ullam exceptionem dari aut fingere aliquos, qui, cum luxuriose viverent, a summo philosopho non reprehenderentur eo nomine dumtaxat, cetera caverent? Superiores tres erant, quae esse possent, quarum est una sola defensa, eaque vehementer. Quae quidem res efficit, ne necesse sit isdem de rebus semper quasi dictata decantare neque a commentariolis suis discedere. Hic si Peripateticus fuisset, permansisset, credo, in sententia, qui dolorem malum dicunt esse, de asperitate autem eius fortiter ferenda praecipiunt eadem, quae Stoici. Qui autem de summo bono dissentit de tota philosophiae ratione dissentit. Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. </p>
> ```

Test comment

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/295)* status: 1 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_1.html, line 10 at r2](http://localhost:8080/reviews/cgiroux86/test/295#-MdMvfEa5vk8Qq9_JUy_:-MdMvfEa5vk8Qq9_JUya:bh2icn1) ([raw file](https://github.com/cgiroux86/test/blob/f4b239814d77a9915227c78404ba7e134ece10aa/large/large_diff_1.html#L10)):*
> ```HTML
> 
> <h2>Primum cur ista res digna odio est, nisi quod est turpis?</h2>
> ```

Another comment

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/295)* status: 1 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_0.html, line 13 at r2](http://localhost:8080/reviews/cgiroux86/test/295#-MdMwId8C3Er4tQb3uHG:-MdMwId8C3Er4tQb3uHH:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/f4b239814d77a9915227c78404ba7e134ece10aa/large/large_diff_0.html#L13)):*
> ```HTML
> <p>Quod non faceret, si in voluptate summum bonum poneret. Et ego: Piso, inquam, si est quisquam, qui acute in causis videre soleat quae res agatur. Somnum denique nobis, nisi requietem corporibus et is medicinam quandam laboris afferret, contra naturam putaremus datum; Nam si amitti vita beata potest, beata esse non potest. Verba tu fingas et ea dicas, quae non sentias? </p>
> 
> <p>Duo Reges: constructio interrete. Infinitio ipsa, quam apeirian vocant, tota ab illo est, tum innumerabiles mundi, qui et oriantur et intereant cotidie. Immo vero, inquit, ad beatissime vivendum parum est, ad beate vero satis. Desideraret enim valitudinem, vacuitatem doloris, appeteret etiam conservationem sui earumque rerum custodiam finemque, sibi constitueret secundum naturam vivere. Quos qui tollunt et nihil posse percipi dicunt, ii remotis sensibus ne id ipsum quidem expedire possunt, quod disserunt. Simul atque natum animal est, gaudet voluptate et eam appetit ut bonum, aspernatur dolorem ut malum. Addebat etiam se in legem Voconiam iuratum contra eam facere non audere, nisi aliter amicis videretur. Quae qui non vident, nihil umquam magnum ac cognitione dignum amaverunt. Bonum integritas corporis: misera debilitas. Concinnus deinde et elegans huius, Aristo, sed ea, quae desideratur, a magno philosopho, gravitas, in eo non fuit; Quis suae urbis conservatorem Codrum, quis Erechthei filias non maxime laudat? </p>
> ```

TEST

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/295)* status: 1 of 151 files reviewed, 6 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_1.html, line 17 at r2](http://localhost:8080/reviews/cgiroux86/test/295#-MdNTF7A1rLaqM2ufdH_:-MdNTF7A1rLaqM2ufdHa:b8uggm7) ([raw file](https://github.com/cgiroux86/test/blob/f4b239814d77a9915227c78404ba7e134ece10aa/large/large_diff_1.html#L17)):*
> ```HTML
> <p>Experiamur igitur, inquit, etsi habet haec Stoicorum ratio difficilius quiddam et obscurius. An me, inquam, nisi te audire vellem, censes haec dicturum fuisse? Si enim, ut mihi quidem videtur, non explet bona naturae voluptas, iure praetermissa est; Octavio fuit, cum illam severitatem in eo filio adhibuit, quem in adoptionem D. Tubulo putas dicere? Respondebo me non quaerere, inquam, hoc tempore quid virtus efficere possit, sed quid constanter dicatur, quid ipsum a se dissentiat. </p>
> 
> <p>Ut alios omittam, hunc appello, quem ille unum secutus est. Sed erat aequius Triarium aliquid de dissensione nostra iudicare. Nam et ille apud Trabeam voluptatem animi nimiam laetitiam dicit eandem, quam ille Caecilianus, qui omnibus laetitiis laetum esse se narrat. Sunt autem, qui dicant foedus esse quoddam sapientium, ut ne minus amicos quam se ipsos diligant. Intrandum est igitur in rerum naturam et penitus quid ea postulet pervidendum; Saepe ab Aristotele, a Theophrasto mirabiliter est laudata per se ipsa rerum scientia; Teneamus enim illud necesse est, cum consequens aliquod falsum sit, illud, cuius id consequens sit, non posse esse verum. Quid igitur dubitamus in tota eius natura quaerere quid sit effectum? Hic si Peripateticus fuisset, permansisset, credo, in sententia, qui dolorem malum dicunt esse, de asperitate autem eius fortiter ferenda praecipiunt eadem, quae Stoici. Sed tempus est, si videtur, et recta quidem ad me. </p>
> ```

COMMENT :)

**Comment by cgiroux86** [comment]
___
*[large/large_diff_1.html, line 23 at r2](http://localhost:8080/reviews/cgiroux86/test/295#-MdNUArr5cjDpNCW6Bw6:-MdNUArr5cjDpNCW6Bw7:bxvrraf) ([raw file](https://github.com/cgiroux86/test/blob/f4b239814d77a9915227c78404ba7e134ece10aa/large/large_diff_1.html#L23)):*
> ```HTML
> <h3>Ut proverbia non nulla veriora sint quam vestra dogmata.</h3>
> 
> <p>Tenent mordicus. Qui igitur convenit ab alia voluptate dicere naturam proficisci, in alia summum bonum ponere? Ergo in eadem voluptate eum, qui alteri misceat mulsum ipse non sitiens, et eum, qui illud sitiens bibat? Si quicquam extra virtutem habeatur in bonis. Id enim volumus, id contendimus, ut officii fructus sit ipsum officium. Nam quibus rebus efficiuntur voluptates, eae non sunt in potestate sapientis. Sin te auctoritas commovebat, nobisne omnibus et Platoni ipsi nescio quem illum anteponebas? Sin autem ad animum, falsum est, quod negas animi ullum esse gaudium, quod non referatur ad corpus. Se dicere inter honestum et turpe nimium quantum, nescio quid inmensum, inter ceteras res nihil omnino interesse. Nihilne est in his rebus, quod dignum libero aut indignum esse ducamus? Mene ergo et Triarium dignos existimas, apud quos turpiter loquare? Ut in geometria, prima si dederis, danda sunt omnia. Itaque eo, quale sit, breviter, ut tempus postulat, constituto accedam ad omnia tua, Torquate, nisi memoria forte defecerit. Quid enim? Nam Pyrrho, Aristo, Erillus iam diu abiecti. </p>
> ```

NEW COMMENT!

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/295)* status: 1 of 151 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_13.html, line 9 at r2](http://localhost:8080/reviews/cgiroux86/test/295#-MdRgotU3puwtrzTdD9I:-MdRgotU3puwtrzTdD9J:b-2depu6) ([raw file](https://github.com/cgiroux86/test/blob/f4b239814d77a9915227c78404ba7e134ece10aa/large/large_diff_13.html#L9)):*
> ```HTML
> <h2>Et certamen honestum et disputatio splendida! omnis est enim de virtutis dignitate contentio.</h2>
> 
> <p>Fatebuntur Stoici haec omnia dicta esse praeclare, neque eam causam Zenoni desciscendi fuisse. Nam his libris eum malo quam reliquo ornatu villae delectari. Sed eum qui audiebant, quoad poterant, defendebant sententiam suam. Rem unam praeclarissimam omnium maximeque laudandam, penitus viderent, quonam gaudio complerentur, cum tantopere eius adumbrata opinione laetentur? Aliter enim explicari, quod quaeritur, non potest. Ita, quem ad modum in senatu semper est aliquis, qui interpretem postulet, sic, isti nobis cum interprete audiendi sunt. Hoc enim identidem dicitis, non intellegere nos quam dicatis voluptatem. Quodsi ipsam honestatem undique pertectam atque absolutam. </p>
> ```

Test comment #1

**Pull request merged**
