### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/431)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
Forst?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Forst?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS8MHo9MPhXpGrU5BD):*
Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>


Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Not?
</blockquote></details>

Done.

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/431)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[-- commits, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/431#-MnS6PmG6yDeU3-uhsLn):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?

**Pull request merged**
