### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by cgiroux86**
Test PR

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/304)

### CODE REVIEW

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 0 of 151 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_139.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Mdvu0Ly1zUDPm-khBCt:-Mdvu0Ly1zUDPm-khBCu:bu6imgl) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_139.html#L3)):*
> ```HTML
> <h1>Eadem nunc mea adversum te oratio est.</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Neque solum ea communia, verum etiam paria esse dixerunt. Scaevola tribunus plebis ferret ad plebem vellentne de ea re quaeri. Hanc in motu voluptatem -sic enim has suaves et quasi dulces voluptates appellat-interdum ita extenuat, ut M. Deque his rebus satis multa in nostris de re publica libris sunt dicta a Laelio. Bestiarum vero nullum iudicium puto. Duo Reges: constructio interrete. Illorum vero ista ipsa quam exilia de virtutis vi! Quam tantam volunt esse, ut beatum per se efficere possit. Cognitio autem haec est una nostri, ut vim corporis animique norimus sequamurque eam vitam, quae rebus iis ipsis perfruatur. </p>
> ```

TESTING

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 0 of 151 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_139.html, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Mdwis8Z-GynIvE4L_8R:-Mdwis8Z-GynIvE4L_8S:bvf2bif) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_139.html#L9)):*
> ```HTML
> <p>Quid, si reviviscant Platonis illi et deinceps qui eorum auditores fuerunt, et tecum ita loquantur? Atqui eorum nihil est eius generis, ut sit in fine atque extrerno bonorum. Parvi enim primo ortu sic iacent, tamquam omnino sine animo sint. Ac tamen, ne cui loco non videatur esse responsum, pauca etiam nunc dicam ad reliquam orationem tuam. Tamen aberramus a proposito, et, ne longius, prorsus, inquam, Piso, si ista mala sunt, placet. Atque hoc loco similitudines eas, quibus illi uti solent, dissimillimas proferebas. </p>
> 
> <p>Quamquam tu hanc copiosiorem etiam soles dicere. Nam, ut sint illa vendibiliora, haec uberiora certe sunt. Quod enim testimonium maius quaerimus, quae honesta et recta sint, ipsa esse optabilia per sese, cum videamus tanta officia morientis? Ratio quidem vestra sic cogit. Atque haec contra Aristippum, qui eam voluptatem non modo summam, sed solam etiam ducit, quam omnes unam appellamus voluptatem. Nam constitui virtus nullo modo potesti nisi ea, quae sunt prima naturae, ut ad summam pertinentia tenebit. Quid affers, cur Thorius, cur Caius Postumius, cur omnium horum magister, Orata, non iucundissime vixerit? </p>
> ```

New comment!

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 0 of 151 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_0.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MdwoXrvERH85dHTjtgO:-MdwoXrvERH85dHTjtgP:b2ngxzh) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_0.html#L3)):*
> ```HTML
> <h1>Apud ceteros autem philosophos, qui quaesivit aliquid, tacet;</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quo modo autem philosophus loquitur? Nec enim haec movere potest appetitum animi, nec ullum habet ictum, quo pellat animum, status hic non dolendi, itaque in hoc eodem peccat Hieronymus. Primum enim, si vera sunt ea, quorum recordatione te gaudere dicis, hoc est, si vera sunt tua scripta et inventa, gaudere non potes. Inquit, cum ego te hac nova lege videam eodem die accusatori responderet tribus horis perorare, in hac me causa tempus dilaturum putas? </p>
> ```

123

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 5 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[—◯— commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me0t-pMEiQ_gPJOa3Tt:-Me0t-pMEiQ_gPJOa3Tu:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/—◯— commits#L1)):*
TEST

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 5 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_139.html, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Mdwis8Z-GynIvE4L_8R:-Me0vy7w4Sk3ohT3H1AD:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_139.html#L9)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

New comment!
</blockquote></details>

Test

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 5 of 151 files reviewed, 5 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_49.html, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me13tfy-fOH-Gu3AuzA:-Me13tfy-fOH-Gu3AuzB:b-3sz5na) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_49.html#L5)):*
> ```HTML
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Est enim aliquid in his rebus probabile, et quidem ita, ut eius ratio reddi possit, ergo ut etiam probabiliter acti ratio reddi possit. Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi. Duo Reges: constructio interrete. De malis autem et bonis ab iis animalibus, quae nondum depravata sint, ait optime iudicari. Nec tamen ullo modo summum pecudis bonum et hominis idem mihi videri potest. Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur. Studet enim meus is audire Cicero quaenam sit istius veteris, quam commemoras, Academiae de finibus bonorum Peripateticorumque sententia. Intellegi quidem, ut propter aliam quampiam rem, verbi gratia propter voluptatem, nos amemus; Ego vero volo in virtute vim esse quam maximam; Et ego: Piso, inquam, si est quisquam, qui acute in causis videre soleat quae res agatur. </p>
> 
> <p>Ipse Epicurus fortasse redderet, ut Sextus Peducaeus, Sex. Cupit enim dícere nihil posse ad beatam vitam deesse sapienti. Theophrastum tamen adhibeamus ad pleraque, dum modo plus in virtute teneamus, quam ille tenuit, firmitatis et roboris. Is enim percontando atque interrogando elicere solebat eorum opiniones, quibuscum disserebat, ut ad ea, quae ii respondissent, si quid videretur, diceret. Hosne igitur laudas et hanc eorum, inquam, sententiam sequi nos censes oportere? </p>
> ```

TEST COMMENT

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 6 of 151 files reviewed, 6 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_19.html, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me144kn4UNQ6_sNiolK:-Me144ko46ZZeatGNfUm:b-8153x3) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_19.html#L5)):*
> ```HTML
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Numquam hoc ita defendit Epicurus neque Metrodorus aut quisquam eorum, qui aut saperet aliquid aut ista didicisset. Duo Reges: constructio interrete. </p>
> 
> <p>Et homini, qui ceteris animantibus plurimum praestat, praecipue a natura nihil datum esse dicemus? Primum non saepe, deinde quae est ista relaxatio, cum et praeteriti doloris memoria recens est et futuri atque inpendentis torquet timor? Et ais, si una littera commota sit, fore tota ut labet disciplina. Mihi quidem Homerus huius modi quiddam vidisse videatur in iis, quae de Sirenum cantibus finxerit. Videmus in quodam volucrium genere non nulla indicia pietatis, cognitionem, memoriam, in multis etiam desideria videmus. Quid enim mihi potest esse optatius quam cum Catone, omnium virtutum auctore, de virtutibus disputare? Quid enim ab antiquis ex eo genere, quod ad disserendum valet, praetermissum est? Quos qui tollunt et nihil posse percipi dicunt, ii remotis sensibus ne id ipsum quidem expedire possunt, quod disserunt. In ipsa enim parum magna vis inest, ut quam optime se habere possit, si nulla cultura adhibeatur. Ex quo intellegitur officium medium quiddam esse, quod neque in bonis ponatur neque in contrariis. Cum autem assumpta ratío est, tanto in dominatu locatur, ut omnia illa prima naturae hulus tutelae subiciantur. Quodsi Graeci leguntur a Graecis isdem de rebus alia ratione compositis, quid est, cur nostri a nostris non legantur? </p>
> ```

TEST

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 6 of 151 files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_20.html, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me168d90C0Mt045tqnx:-Me168d90C0Mt045tqny:b3rs795) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_20.html#L9)):*
> ```HTML
> <p>Quid, si non modo utilitatem tibi nullam afferet, sed iacturae rei familiaris erunt faciendae, labores suscipiendi, adeundum vitae periculum? Estne, quaeso, inquam, sitienti in bibendo voluptas? Etenim semper illud extra est, quod arte comprehenditur. Vitae autem degendae ratio maxime quidem illis placuit quieta. </p>
> 
> <p>Et quidem illud ipsum non nimium probo et tantum patior, philosophum loqui de cupiditatibus finiendis. Illa videamus, quae a te de amicitia dicta sunt. Quod idem cum vestri faciant, non satis magnam tribuunt inventoribus gratiam. Dic in quovis conventu te omnia facere, ne doleas. Quod, inquit, quamquam voluptatibus quibusdam est saepe iucundius, tamen expetitur propter voluptatem. Scaevola tribunus plebis ferret ad plebem vellentne de ea re quaeri. </p>
> ```

TESTING 123...

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 6 of 151 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

___
*[large/large_diff_105.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me17NJ62nZykjuEq-CV:-Me17NJ62nZykjuEq-CW:b8gohym) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_105.html#L3)):*
> ```HTML
> <h1>Hoc ipsum elegantius poni meliusque potuit.</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et quidem illud ipsum non nimium probo et tantum patior, philosophum loqui de cupiditatibus finiendis. Itaque et vivere vitem et mori dicimus arboremque et novellan et vetulam et vigere et senescere. Si qua in iis corrigere voluit, deteriora fecit. Conferam tecum, quam cuique verso rem subicias; Duo Reges: constructio interrete. Atqui, inquit, si Stoicis concedis ut virtus sola, si adsit vitam efficiat beatam, concedis etiam Peripateticis. </p>
> ```

TESTING 456...

**Comment by chg1017** [comment]
___
*[large/large_diff_49.html, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me13tfy-fOH-Gu3AuzA:-Me1TIbbEojTaIX7Q4B4:b32w0x) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_49.html#L5)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TEST COMMENT 
</blockquote></details>

OK

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 6 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 11 of 151 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[—◯— commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me0t-pMEiQ_gPJOa3Tt:-Me1REp3-XLaGENPhI0q:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/—◯— commits#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

Done.
___
*[large/large_diff_19.html, line 5 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me144kn4UNQ6_sNiolK:-Me5Lgby1bv2oM6tBLAC:b-81nndn) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_19.html#L5)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST 
</blockquote></details>

Reply

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 2 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 13 of 151 files reviewed, 6 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 13 of 151 files reviewed, 6 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[large/large_diff_139.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Mdvu0Ly1zUDPm-khBCt:-Me5jIGY2ttbV36Znwrx:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_139.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TESTING 
</blockquote></details>

TEST

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 14 of 151 files reviewed, 6 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 2 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 16 of 151 files reviewed, 7 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[large/large_diff_139.html, line 7 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeAdPH40V4d2RGmOZBj:-MeAdPH40V4d2RGmOZBk:b-vbm1re) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/large/large_diff_139.html#L7)):*
> ```HTML
> <h2>Idemque diviserunt naturam hominis in animum et corpus.</h2>
> 
> <p>Quod cum ita sit, perspicuum est omnis rectas res atque laudabilis eo referri, ut cum voluptate vivatur. Sit voluptas non minor in nasturcio illo, quo vesci Persas esse solitos scribit Xenophon, quam in Syracusanis mensis, quae a Platone graviter vituperantur; Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. Aliis esse maiora, illud dubium, ad id, quod summum bonum dicitis, ecquaenam possit fieri accessio. Igitur ne dolorem quidem. </p>
> ```

hdfdfhkdajsf

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 16 of 151 files reviewed, 8 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[large/large_diff_72.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeAsjF647P7_FgKDD50:-MeAsjF647P7_FgKDD51:b80cxax) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_72.html#L3)):*
> ```HTML
> <h1>Nonne igitur tibi videntur, inquit, mala?</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Immo istud quidem, inquam, quo loco quidque, nisi iniquum postulo, arbitratu meo. Cur igitur, cum de re conveniat, non malumus usitate loqui? Vadem te ad mortem tyranno dabis pro amico, ut Pythagoreus ille Siculo fecit tyranno? Partim cursu et peragratione laetantur, congregatione aliae coetum quodam modo civitatis imitantur; Idcirco enim non desideraret, quia, quod dolore caret, id in voluptate est. Duo Reges: constructio interrete. Maximas vero virtutes iacere omnis necesse est voluptate dominante. Tenesne igitur, inquam, Hieronymus Rhodius quid dicat esse summum bonum, quo putet omnia referri oportere? Sed quid minus probandum quam esse aliquem beatum nec satis beatum? Epicurus autem cum in prima commendatione voluptatem dixisset, si eam, quam Aristippus, idem tenere debuit ultimum bonorum, quod ille; </p>
> ```

DRAFRTS

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 139 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 8 unresolved discussions (waiting on @chg1017)

___
*[—◯— commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me0t-pMEiQ_gPJOa3Tt:-MeAt2F35fyq6OI9iAvH:bhjg70) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/—◯— commits#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Replying!

**Review by girouxchris1017 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_105.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me17NJ62nZykjuEq-CV:-MeAuIMr2_9-b5mpk-pV:b-wvvgee) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_105.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TESTING 456...
</blockquote></details>

BLOCKING

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_139.html, line 7 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeAdPH40V4d2RGmOZBj:-MeAuxHv6iE2FZbafm3A:bu6imgl) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/large/large_diff_139.html#L7)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

hdfdfhkdajsf
</blockquote></details>

TESTING

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 7 unresolved discussions (waiting on @chg1017 and @girouxchris1017)

___
*[large/large_diff_139.html, line 7 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeAdPH40V4d2RGmOZBj:-MeAv9t5-b5JFq08XVzT:bu5dgly) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/large/large_diff_139.html#L7)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

TESTING 
</blockquote></details>

Replied

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_0.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MdwoXrvERH85dHTjtgO:-MeAvMsP1vjC8AzW8G-d:byv273z) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_0.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

123
</blockquote></details>

Rplied
___
*[large/large_diff_139.html, line 7 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeAdPH40V4d2RGmOZBj:-MeAvRPU9kpLfV_ub1Tj:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/large/large_diff_139.html#L7)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Replied
</blockquote></details>

Test
___
*[large/large_diff_20.html, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me168d90C0Mt045tqnx:-MeAvPYx7bOHQcgTJB07:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_20.html#L9)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

TESTING 123...
</blockquote></details>

Test
___
*[large/large_diff_72.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeAsjF647P7_FgKDD50:-MeAvQUM1H47DQONnVIm:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_72.html#L3)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

DRAFRTS
</blockquote></details>

TEST

**Review by girouxchris1017 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[—◯— commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me0t-pMEiQ_gPJOa3Tt:-MeB-qUs3lO6FELnv_Dt:b-d91tpf) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/—◯— commits#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Replying! 
</blockquote></details>

Replying again

**Review by girouxchris1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[—◯— commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me0t-pMEiQ_gPJOa3Tt:-MeB0bPM6oOsgYKgS0bN:b7r5xui) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/—◯— commits#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Replying again
</blockquote></details>

Comment

**Review by girouxchris1017 — APPROVED** [review]
> Reviewed 1 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[—◯— commits, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-Me0t-pMEiQ_gPJOa3Tt:-MeB6FknC1lN7ep-rsND:b80cyq1) ([raw file](https://github.com/cgiroux86/test/blob/456f944ed9e72e09e75a0b76d3a50c02c984d1f1/—◯— commits#L1)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Comment
</blockquote></details>

DRAFTS

**Review by girouxchris1017 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 7 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 8 of 151 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 2 unresolved discussions (waiting on @chg1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[large/large_diff_49.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeB9CQBAXMJNd40Qfvd:-MeB9CQBAXMJNd40Qfve:bvf2bif) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_49.html#L3)):*
> ```HTML
> <h1>Refert tamen, quo modo.</h1>
> 
> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Est enim aliquid in his rebus probabile, et quidem ita, ut eius ratio reddi possit, ergo ut etiam probabiliter acti ratio reddi possit. Sed id ne cogitari quidem potest quale sit, ut non repugnet ipsum sibi. Duo Reges: constructio interrete. De malis autem et bonis ab iis animalibus, quae nondum depravata sint, ait optime iudicari. Nec tamen ullo modo summum pecudis bonum et hominis idem mihi videri potest. Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur. Studet enim meus is audire Cicero quaenam sit istius veteris, quam commemoras, Academiae de finibus bonorum Peripateticorumque sententia. Intellegi quidem, ut propter aliam quampiam rem, verbi gratia propter voluptatem, nos amemus; Ego vero volo in virtute vim esse quam maximam; Et ego: Piso, inquam, si est quisquam, qui acute in causis videre soleat quae res agatur. </p>
> ```

New comment!

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: all files reviewed, 3 unresolved discussions (waiting on @chg1017)

___
*[large/large_diff_49.html, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/304#-MeB9CQBAXMJNd40Qfvd:-MeB9IpM1fLMabovFkt9:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/487ed303b1570629d8982b38c289b3164f29a3fd/large/large_diff_49.html#L3)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

New comment!
</blockquote></details>

Done.

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 151 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 1 of 151 files reviewed, 3 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 1 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/304#-MeBHGX202LvmNE9nQtx:-MeBHGX202LvmNE9nQty:b-wvvgee) (no related file):*
BLOCKING

---

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 151 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 2 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 151 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 3 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: 3 of 151 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/304#-MeBHGX202LvmNE9nQtx:-MeBJdrY0bzfE1LU0Rh_:b-896fix) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

BLOCKING
</blockquote></details>

Done.

---

**Review by chg1017 — APPROVED** [review]
> Reviewed 148 of 151 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 151 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
