### PR TITLE
PR#10

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/161)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/161)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 7 at r1](http://localhost:8080/reviews/cgiroux86/test/161#-MYlbJt0Aj8X2ZjmuBOy:-MYlbJt0Aj8X2ZjmuBOz:bc0gei3) ([raw file](https://github.com/cgiroux86/test/blob/2faf489b629e0d7651db2a7c8404b4bfcfdf182d/mainfile1.js#L7)):*
> ```JavaScript
> console.log('4th commit');
> console.log('5th commit');
> console.log('6th commit');
> ```

testing

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/161)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 2 at r1](http://localhost:8080/reviews/cgiroux86/test/161#-MYlhdNz27kyQxcRk0e7:-MYlhdO-0G7p39DARpyW:bk0k3zo) ([raw file](https://github.com/cgiroux86/test/blob/2faf489b629e0d7651db2a7c8404b4bfcfdf182d/mainfile1.js#L2)):*
> ```JavaScript
> 
> console.log('HELLO WORLD!');
> ```

Another test

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/161)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/161#-MYliHh3DLHPe4hVvOtz:-MYliHh3DLHPe4hVvOu-:bchnkya) ([raw file](https://github.com/cgiroux86/test/blob/2faf489b629e0d7651db2a7c8404b4bfcfdf182d/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Second thought

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/161)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[mainfile1.js, line 6 at r1](http://localhost:8080/reviews/cgiroux86/test/161#-MYlkkU4Ap2HCtcy92H1:-MYlkkU4Ap2HCtcy92H2:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/2faf489b629e0d7651db2a7c8404b4bfcfdf182d/mainfile1.js#L6)):*
> ```JavaScript
> console.log('3rd commit');
> console.log('4th commit');
> console.log('5th commit');
> ```

Test

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/161)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

___
*[mainfile1.js, line 9 at r1](http://localhost:8080/reviews/cgiroux86/test/161#-MYtftFC5qC7Jibymvpb:-MYtftFC5qC7Jibymvpc:bnppngj) ([raw file](https://github.com/cgiroux86/test/blob/2faf489b629e0d7651db2a7c8404b4bfcfdf182d/mainfile1.js#L9)):*
> ```JavaScript
> console.log('6th commit');
> console.log('7th commit');
> console.log('8th commit');
> ```

Unnecessary.

**Pull request merged**
