### PR TITLE
Merge pull request #470 from cgiroux86/testing

### PR DESCRIPTION
**Pull request by cgiroux86**
first commit

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/471)

### CODE REVIEW

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[test_node, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/471#-MtMyN9u6Sz2JZBml2JP:-MtMyN9u6Sz2JZBml2JQ:b-lnmth3) ([raw file](https://github.com/cgiroux86/test/blob/ed32d9aa311b6fe8963e500bc6d5b046195ec17f/test_node#L3)):*
> ```
> #!/usr/bin/env node
> 
> const test = '123';
> ```

why inline?

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

___
*[test_node, line 3 at r1](http://localhost:8080/reviews/cgiroux86/test/471#-MtMyN9u6Sz2JZBml2JP:-MtN1n4eCtit4ijgvUHY:b-896fix) ([raw file](https://github.com/cgiroux86/test/blob/ed32d9aa311b6fe8963e500bc6d5b046195ec17f/test_node#L3)):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

why inline?
</blockquote></details>

Done.

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/471)* status: all files reviewed, 1 unresolved discussion (waiting on @girouxchris1017)

**Pull request merged**
