### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by cgiroux86**
PR#1

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/330)

### CODE REVIEW

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfnzzgL5t4gPhiV_exV:bqfobvd) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!
> ```



[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/i4sY6sYHi2Y39x0l72LmSsGy/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-Mfo-SLt-9uuu33PaU5E:-Mfo-SLt-9uuu33PaU5F:bgvpjii) ([raw file](https://github.com/cgiroux86/test/blob/a3fcb8f4c14dbaa3dd821b1c78d9b64893c41df2/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!!!
> ```

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/1KB86r6MTu5Ev10k9NTxYru3/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-Mfo-Ytt8LCQWpL2WojK:b-6vcjbc) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/i4sY6sYHi2Y39x0l72LmSsGy/sample-mp4-file.mp4)
</blockquote></details>


[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/tK4j5YhsBAtd0hR87crCX1k4/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-Mfo-SLt-9uuu33PaU5E:-Mfo-hZq6D2-kwZ0fci9:b-b2op25) ([raw file](https://github.com/cgiroux86/test/blob/a3fcb8f4c14dbaa3dd821b1c78d9b64893c41df2/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/1KB86r6MTu5Ev10k9NTxYru3/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/hia0TaVzT91hermazqJLuMdh/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
https://user-images.githubusercontent.com/59579733/127565773-d7c49f97-921c-4c4b-8bf0-5c06d0d92bb6.mp4

**Comment by chg1017** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrJ6_W2jpCdHyp0YZ5:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/tK4j5YhsBAtd0hR87crCX1k4/sample-mp4-file.mp4)
</blockquote></details>

Test

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrJHen6LsDAfx6CQPT:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Test

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrKMcO9r3nqRLwUL0L:b-vhkcs5) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Test
</blockquote></details>

Testing

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrLAmr0upQYogYY6IV:b-nd91jc) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Testing
</blockquote></details>

More test

**Comment by chg1017** [comment]
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cgiroux86/test/330#-MfrLtJl55x0FXVGRZcz:-MfrLtJl55x0FXVGRZd-:b-8zijsc) ([raw file](https://github.com/cgiroux86/test/blob/a3fcb8f4c14dbaa3dd821b1c78d9b64893c41df2/-- commits#L2)):*
Test comment

**Comment by chg1017** [comment]
___
*[test.txt, line 1 at r1](https://reviewable.io/reviews/cgiroux86/test/330#-MfrN25J8Yqdzb5xf1Xs:-MfrN25J8Yqdzb5xf1Xt:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!
> ```

TEST

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrNIOR9SUTT_KEggGi:bh2icn1) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

More test
</blockquote></details>

Another comment

**Review by chg1017 — COMMENTED** [review]
> Dismissed @cgiroux86 from a discussion.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/330)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @cgiroux86, @chg101786, and @girouxchris1017)

___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrNLWR6QM_VhWr-NBa:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Another comment
</blockquote></details>

TEST

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrNzJvDilbmNe-pHsc:b-wvvjmu) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

BLOCKED!

**Comment by chg1017** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrO3e2-sH9FpHeABGY:bb73z13) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

BLOCKED!
</blockquote></details>

TEST

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-MfnzzgL5t4gPhiV_exU:-MfrcQdy7IWENHYP4fRm:bb74njr) ([raw file](https://github.com/cgiroux86/test/blob/3dce5653d043093ba261a2c3aacbf93b062b4876/test.txt#L1)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

Test

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-Mfo-SLt-9uuu33PaU5E:-MfrqaMe90cf7HxWgrBq:b19e5nf) ([raw file](https://github.com/cgiroux86/test/blob/a3fcb8f4c14dbaa3dd821b1c78d9b64893c41df2/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/hia0TaVzT91hermazqJLuMdh/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/PQG3w_Fdh3NyfhRxul1JOEfz/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-Mfo-SLt-9uuu33PaU5E:-MfsATo7--whA9OXJvni:b-ya39hd) ([raw file](https://github.com/cgiroux86/test/blob/a3fcb8f4c14dbaa3dd821b1c78d9b64893c41df2/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/PQG3w_Fdh3NyfhRxul1JOEfz/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/kJ9OzmMqjfBeoqt_-caKVRJE/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-Mfo-SLt-9uuu33PaU5E:-MfsApfID33RrGajBxLO:bapvrk1) ([raw file](https://github.com/cgiroux86/test/blob/a3fcb8f4c14dbaa3dd821b1c78d9b64893c41df2/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/kJ9OzmMqjfBeoqt_-caKVRJE/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/FCybuCsxgBKtEnd9UIGB52mw/sample-mp4-file.mp4)

**Comment by cgiroux86** [comment]
___
*[test.txt, line 1 at r1](http://localhost:8080/reviews/cgiroux86/test/330#-Mfo-SLt-9uuu33PaU5E:-MfsSm_D8FkbkripIXDM:b-812ura) ([raw file](https://github.com/cgiroux86/test/blob/a3fcb8f4c14dbaa3dd821b1c78d9b64893c41df2/test.txt#L1)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/FCybuCsxgBKtEnd9UIGB52mw/sample-mp4-file.mp4)
</blockquote></details>

[sample-mp4-file.mp4](https://s3.amazonaws.com/reviewable-dev/images/reviewable-dev-chris-default-rtdb/59579733/cID0xqz7KhIxaWOYlG2xpARf/sample-mp4-file.mp4)

**Pull request merged**
