### PR TITLE
PR#29

### PR DESCRIPTION
**Pull request by cgiroux86**
Test PR

---
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test/218)

### CODE REVIEW

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbflLWG7Z9yV3ZZ4APu:-MbflLWG7Z9yV3ZZ4APv:b-wvvjmu) (no related file):*
BLOCKED!

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbflLWG7Z9yV3ZZ4APu:-Mbfq7YM4pLDnOTDgHwO:bb74njr) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

BLOCKED!
</blockquote></details>

Test

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbfqMgF7fsnL9LGoWTn:-MbfqMgF7fsnL9LGoWTo:b-wvvjmu) (no related file):*
BLOCKED!

---

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

___
*[test.txt, line 1 at r3](http://localhost:8080/reviews/cgiroux86/test/218#-MbfwzIF2rDLC8jQLzCN:-MbfwzIF2rDLC8jQLzCO:bq9rql6) ([raw file](https://github.com/cgiroux86/test/blob/329d44335f1e6b7510033f48de5fd3ce771e7530/test.txt#L1)):*
> ```help
> HELLO REVIEWABLE!!!
> ```

Blocking

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
Test

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218#-:-MbhcKSr7tLHO8JMEAs9:bb74njr)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
Test

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218#-:-MbhfZjDA_I4x-ykhX6n:bb74njr)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbfqMgF7fsnL9LGoWTn:-MbiIFXVCg6e4NrbeIZY:bb74njr) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

BLOCKED!
</blockquote></details>

Test

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-Mbh8Q6TAXRKDup3XpnH:-MbiIWGN8GjyZELt5ZRH:b4ycwog) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TESTING!
</blockquote></details>

Computing?

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-Mbh8Q6TAXRKDup3XpnH:-MbiIrWV-HfgpvWqvtBs:brcpp1p) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Computing?
</blockquote></details>

Compute?

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-Mbh8Q6TAXRKDup3XpnH:-MbiJ6Gu4dxCCSVEStZ_:b-4f81z5) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Compute?
</blockquote></details>

Computer?

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-Mbh8Q6TAXRKDup3XpnH:-MbiJ_bx5_tRZsXaCxng:bxbiyps) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Computer?
</blockquote></details>

Pending Test

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-Mbh8Q6TAXRKDup3XpnH:-MbiJlWW2YgChtZ3p5tg:bo7oo83) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Pending Test
</blockquote></details>

Another pending test 

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbflLWG7Z9yV3ZZ4APu:-MbiK02K5rx3U5j07XJR:bb74njr) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Test

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbfqMgF7fsnL9LGoWTn:-MbiKE_S9XFMMwEHmKNI:bb74njr) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Test

---

**Review by chg1017 — COMMENTED** [review]
Yrdy

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218#-:-MbiKeZk4tGYVhgic7p2:bb783rn)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbfqMgF7fsnL9LGoWTn:-MbiM4Ho91chZ6hXSX5b:bb73z13) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

TEST

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbfqMgF7fsnL9LGoWTn:-MbiMZRE3-iPR-ByVvSr:bb73z13) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

TEST
</blockquote></details>

TEST

---

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by girouxchris1017 — COMMENTED** [review]
Deferring

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218#-:-MbiXu3L8RcXuGhEJxqt:b-4cuw9v)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbflLWG7Z9yV3ZZ4APu:-MbiZWQc-azV2yjbz0-y:bb74njr) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Test
</blockquote></details>

Test

---

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MblTJUqAgwKrdBaJ0G7:-MblTJUqAgwKrdBaJ0G8:b-e8sxg4) (no related file):*
Parking?

---

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 4 files at r8.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[added.py, line 1 at r8](http://localhost:8080/reviews/cgiroux86/test/218#-Mbm8rY18QqRwTlyWZ5V:-Mbm8rY18QqRwTlyWZ5W:b-e8sxgy) ([raw file](https://github.com/cgiroux86/test/blob/d4c665c93a13e4d7824771ee6155859a8c21caa5/added.py#L1)):*
> ```Python
> print('This is an added file!!');
> ```

Parking!

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[file1.js, line 2 at r9](http://localhost:8080/reviews/cgiroux86/test/218#-Mbm8xnh0H7gnF0Ezk_z:-Mbm8xni27ScVvCz_dFh:byak2ab) ([raw file](https://github.com/cgiroux86/test/blob/c6e69282886f6f27fc4783399a587079292b8e57/file1.js#L2)):*
> ```JavaScript
> 
> console.log('initiating test sequence in 3...2...1...0!!!!');
> ```

PARKED!

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 4 files at r8.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

___
*[file1.js, line 2 at r9](http://localhost:8080/reviews/cgiroux86/test/218#-Mbm8xnh0H7gnF0Ezk_z:-MbmAy7i6TwhaT9pLCW_:b-ctq2wf) ([raw file](https://github.com/cgiroux86/test/blob/c6e69282886f6f27fc4783399a587079292b8e57/file1.js#L2)):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

PARKED!
</blockquote></details>

Parked again?

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbmCUo9C3C7rMrrpTCY:-MbmCUo9C3C7rMrrpTCZ:bdbrg83) (no related file):*
PARKING THIS.

---

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r10.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 2 files at r9.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r12.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 3 files at r13.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 4 of 6 files reviewed, 8 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 3 files at r13.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by chg1017 — COMMENTED** [review]
> Reviewed 1 of 3 files at r13.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: all files reviewed, 8 unresolved discussions (waiting on @cgiroux86 and @chg1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbmmJ8S-aEbpfRgdTkq:-MbmmJ8T-QCph66pB-TS:bq9rql6) (no related file):*
Blocking

---

**Review by chg1017 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbmmJ8S-aEbpfRgdTkq:-MbmmTb1A21dCG1LDkA-:bg0hc6m) (no related file):*
<details><summary><i>Previously, girouxchris1017 wrote…</i></summary><blockquote>

Blocking
</blockquote></details>

Blocked back.

---

**Review by girouxchris1017 — COMMENTED** [review]
> Reviewed 1 of 1 files at r14.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: all files reviewed, 9 unresolved discussions (waiting on @cgiroux86, @chg1017, and @girouxchris1017)

**Review by girouxchris1017 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test/218)* status: 7 of 8 files reviewed, 9 unresolved discussions (waiting on @cgiroux86 and @chg1017)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test/218#-MbmmJ8S-aEbpfRgdTkq:-Mbn-As10FWgCVnMi0Sk:bq9n3yx) (no related file):*
<details><summary><i>Previously, chg1017 wrote…</i></summary><blockquote>

Blocked back.
</blockquote></details>

BL:OCKING BACKJ

---

**Pull request merged**
